#!/usr/bin/env python
import os
import sys
import shutil


def modify(file, changesets):
    shutil.copy(file, ".tmpfile")  # this can preserve the file permission
    replaced = False
    with open(file, 'r') as infile, open(".tmpfile", 'w') as outfile:
        for line in infile:
            if not replaced:
                for key, value in changesets.items():
                    if key in line:
                        line = line.replace(key, value)
                        replaced = True
            outfile.write(line)
    os.replace(".tmpfile", file)


# set the current directory to HOMErrfs
mypath = os.path.dirname(os.path.abspath(__file__))
os.chdir(os.path.join(mypath, "../.."))

# check whether a given modification has been made to avoid a second run of this script
already_modified = False
with open("jobs/JRRFS_JEDIVAR", 'r') as infile:
    for line in infile:
        if 'mkdir -p "${HOME}/rrfstmp_${PDY}${cyc}"' in line:
            already_modified = True
            break
if already_modified:
    print("It is expected to run 'gaea_patch' in a clean git status")
    print("It looks like target files have been modified")
    print("Run 'git status' to check what files have been modified")
    print("Run 'git checkout <file>' to undo changes")
    sys.exit()

# tweak 1 ----------------------------------------------------------
myfile = "parm/jedivar.yaml"
changesets = {
        "filename: mpasout.nc": "filename: ana.nc",
}
modify(myfile, changesets)

# tweak 2 ----------------------------------------------------------
myfile = "jobs/JRRFS_JEDIVAR"
changesets = {
    'mkdir -p "${DATA}"':
    'mkdir -p "${UMBRELLA_JEDIVAR_DATA}"\nrm -rf "${HOME}/rrfstmp_${PDY}${cyc}"\nmkdir -p "${HOME}/rrfstmp_${PDY}${cyc}"\nln -snf "${HOME}/rrfstmp_${PDY}${cyc}"  "${DATA}"',
}
modify(myfile, changesets)

# tweak 3 ----------------------------------------------------------
myfile = "scripts/exrrfs_jedivar.sh"
changesets = {
    '# ncks increments to cold_start IC':
    '''# ncks increments to cold_start IC
  # move ${DATA} from ${HOME} to ${UMBRELLA_JEDIVAR_DATA}
  cd "${UMBRELLA_JEDIVAR_DATA}"
  rm -rf "${DATA}"
  mv "${HOME}/rrfstmp_${PDY}${cyc}" "${DATA}"
  cd "${DATA}" || exit 1

  var_list="pressure_p,rho,qv,qc,qr,qi,qs,qg,ni,nr,ng,nc,nifa,nwfa,volg,surface_pressure,theta,u,uReconstructZonal,uReconstructMeridional,refl10cm,w"
  ncks -O -C -x -v ${var_list} ${initial_file} tmp.nc
  ncks -A -v ${var_list} ana.nc tmp.nc
  export err=$?
  err_chk
  mv tmp.nc "${initial_file}"
  mv ana.nc ..
  cp "${initial_file}"  "${COMOUT}/jedivar/${WGF}/mpasout.${timestr}.nc"'''
}
modify(myfile, changesets)

# tweak 4 ----------------------------------------------------------
myfile = "scripts/exrrfs_jedivar.sh"
changesets = {
    'echo "INFO: No DA at the cold start cycle"':
    '''echo "INFO: No DA at the cold start cycle"
  # move ${DATA} from ${HOME} to ${UMBRELLA_JEDIVAR_DATA}
  cd "${UMBRELLA_JEDIVAR_DATA}"
  rm -rf "${DATA}"
  mv "${HOME}/rrfstmp_${PDY}${cyc}" "${DATA}"
  cd "${DATA}" || exit 1'''
}
modify(myfile, changesets)

# remove 11 lines from scripts/exrrfs_jedivar.sh
file = "scripts/exrrfs_jedivar.sh"
shutil.copy(file, ".tmpfile")  # this can preserve the file permission
with open(file, 'r') as infile, open(".tmpfile", 'w') as outfile:
    skip = False
    knt = 0
    for line in infile:
        if 'if [[ ${start_type} == "cold" ]]; then' in line:
            skip = True
            knt +=1
        elif skip and knt == 11:
            skip = False
        elif skip:
            knt += 1
        if not skip:
            outfile.write(line)
os.replace(".tmpfile", file)

print("Done\nNow your rrfs-workflow can run highres (such as conus3km) JEDIVAR on Gaea")
