#!/usr/bin/env bash

t133=aircar_airTemperature_133                                                                                                                                         q133=aircar_specificHumidity_133                                                   
uv233=aircar_winds_233
t130=aircft_airTemperature_130           
t131=aircft_airTemperature_131
t134=aircft_airTemperature_134
t135=aircft_airTemperature_135
q134=aircft_specificHumidity_134
uv230=aircft_winds_230
uv231=aircft_winds_231
uv234=aircft_winds_234
uv235=aircft_winds_235
t120=adpupa_airTemperature_120
q120=adpupa_specificHumidity_120
ps120=adpupa_stationPressure_120
uv220=adpupa_winds_220
t181=adpsfc_airTemperature_181
t187=adpsfc_airTemperature_187
q181=adpsfc_specificHumidity_181
q187=adpsfc_specificHumidity_187
ps181=adpsfc_stationPressure_181
ps187=adpsfc_stationPressure_187
uv281=adpsfc_winds_281
uv287=adpsfc_winds_287
t188=msonet_airTemperature_188
q188=msonet_specificHumidity_188
ps188=msonet_stationPressure_188
uv288=msonet_winds_288
uv227=proflr_winds_227
t126=rassda_airTemperature_126
t180=sfcshp_airTemperature_180
q180=sfcshp_specificHumidity_180
ps180=sfcshp_stationPressure_180
uv280=sfcshp_winds_280
uv224=vadwnd_winds_224
amsua_n19=satellite_amsua_n19
amsua_n20=satellite_atms_n20
atmos_npp=satellite_atms_npp

#export OBS_TYPE_USE="t133,q133,uv233,t130,t131,t134,t135,q134,uv230,uv231,uv234,uv235,t120,q120,ps120,uv220,t181,t187,q181,q187,\
#ps181,ps187,uv281,uv287,t188,q188,ps188,uv288,uv227,t126,t180,q180,ps180,uv280,uv224,amsua_n19,amsua_n20,atmos_npp"
