#!/usr/bin/env python
#
import sys
import os
from pathlib import Path
import shutil

if len(sys.argv) < 2:
    print(f"Usage: {sys.argv[0]} <filename/directory>")
    exit()
# ~~
tmp = sys.argv[1].rstrip("/")
files = []
if os.path.isdir(tmp):  # or tmp=="." or tmp=="..":
    for file in Path(tmp).glob("*"):  # use rglob for recursively glob
        if file.is_file():
            files.append(file)
else:
    for arg in sys.argv[1:]:
        if Path(arg).exists:
            files.append(arg)

for filename in files:
    # found whether any lines contain trailing whitespaces
    found = False
    with open(filename, 'r', encoding='utf-8') as file:
        for line_number, line in enumerate(file, start=1):
            lineB = line.rstrip('\n')
            if lineB.rstrip() != lineB:  # Check if trailing whitespaces exists
                found = True
                break
    # if found, remove the trailing whitespaces
    if found:
        shutil.copy(filename, f'{filename}_WHITESPACE')
        with open(f'{filename}_WHITESPACE', 'r', encoding='utf-8') as infile, open(filename, 'w', encoding='utf-8') as outfile:
            for line in infile:
                outfile.write(line.rstrip() + '\n')
        print(f'done, original files saved as {filename}_WHITESPACE')
