#!/usr/bin/env bash

source /etc/profile

module load rocoto

rocotostat -w rrfs.xml -d rrfs.db -c all > stat

echo "----------" > ./DEAD
{
    grep DEAD stat
    grep LOST stat
    grep UNKN stat
    echo "#Dead: $(grep DEAD stat | wc | tr -s " " | cut -f 2 -d " ")"
    echo "#Lost: $(grep LOST stat | wc | tr -s " " | cut -f 2 -d " ")"
} >> ./DEAD

echo "----------" > ./RUN
{
    grep RUN stat | tr -s " " | cut -f 1,2,4 -d " "
    grep QUE stat | tr -s " " | cut -f 1,2,4 -d " "
    echo "#Succeeded: $(grep SUC stat | wc | tr -s " " | cut -f 2 -d " ")"
    echo "#Running:   $(grep RUN stat | wc | tr -s " " | cut -f 2 -d " ")"
    echo "#Queued:    $(grep QUE stat | wc | tr -s " " | cut -f 2 -d " ")"
    echo "#Dead:      $(grep DEA stat | wc | tr -s " " | cut -f 2 -d " ")"
    echo "#Lost:      $(grep LOS stat | wc | tr -s " " | cut -f 2 -d " ")"
    echo "#Unknwn:    $(grep UNK stat | wc | tr -s " " | cut -f 2 -d " ")"
    date
} >> ./RUN
