#!/usr/bin/env bash
source /etc/profile
module load rocoto
rocotostat -w rrfs.xml -d rrfs.db -c all > stat
echo "----------" > ./DEAD
grep DEAD stat >> ./DEAD
grep LOST stat >> ./DEAD
grep UNKN stat >> ./DEAD
echo "#Dead: `grep DEAD stat | wc | tr -s " " | cut -f 2 -d " "`" >> ./DEAD
echo "#Lost: `grep LOST stat | wc | tr -s " " | cut -f 2 -d " "`" >> ./DEAD

echo "----------" > ./RUN
echo "`grep RUN stat | tr -s " " | cut -f 1,2,4 -d " "`" >> ./RUN
echo "`grep QUE stat | tr -s " " | cut -f 1,2,4 -d " "`" >> ./RUN
echo "#Succeeded: `grep SUC stat | wc | tr -s " " | cut -f 2 -d " "`" >> ./RUN
echo "#Running:   `grep RUN stat | wc | tr -s " " | cut -f 2 -d " "`" >> ./RUN
echo "#Queued:    `grep QUE stat | wc | tr -s " " | cut -f 2 -d " "`" >> ./RUN
echo "#Dead:      `grep DEA stat | wc | tr -s " " | cut -f 2 -d " "`" >> ./RUN
echo "#Lost:      `grep LOS stat | wc | tr -s " " | cut -f 2 -d " "`" >> ./RUN
echo "#Unknwn:    `grep UNK stat | wc | tr -s " " | cut -f 2 -d " "`" >> ./RUN
echo "`date`" >> ./RUN
