#!/usr/bin/env bash

cyctime=$1
taskname=$2

echo "$cyctime"
echo "$taskname"

if [[ $taskname == "" ]]; then
  rocotorewind -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c "$cyctime" -a
else
  rocotorewind -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c "$cyctime" -t "$taskname"
fi
