#!/usr/bin/env bash

rocotostat -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -c all > stat

total_tasks=$(grep -E '^[0-9]{10}' stat | grep -v '^210001010100' | wc -l)
succeeded=$(grep SUC stat | wc -l)

percent_complete=$(awk -v s="$succeeded" -v t="$total_tasks" 'BEGIN {
    if (t>0) printf "%.1f", 100*s/t; else print 0
}')

echo "----------" > ./DEAD
{
    grep DEAD stat
    grep LOST stat
    grep UNKN stat
    echo "#Dead: $(grep DEAD stat | wc | tr -s " " | cut -f 2 -d " ")"
    echo "#Lost: $(grep LOST stat | wc | tr -s " " | cut -f 2 -d " ")"
} >> ./DEAD

echo "----------" > ./RUN
{
    grep RUN stat | tr -s " " | cut -f 1,2,4 -d " "
    grep QUE stat | tr -s " " | cut -f 1,2,4 -d " "
    echo "#Succeeded: $(grep SUC stat | wc | tr -s " " | cut -f 2 -d " ")"
    echo "#Running:   $(grep RUN stat | wc | tr -s " " | cut -f 2 -d " ")"
    echo "#Queued:    $(grep QUE stat | wc | tr -s " " | cut -f 2 -d " ")"
    echo "#Dead:      $(grep DEA stat | wc | tr -s " " | cut -f 2 -d " ")"
    echo "#Lost:      $(grep LOS stat | wc | tr -s " " | cut -f 2 -d " ")"
    echo "#Unknwn:    $(grep UNK stat | wc | tr -s " " | cut -f 2 -d " ")"
    echo ""
    echo "#Total tasks: ${total_tasks}"
    echo "#Complete:    ${percent_complete}%"
    echo ""
    date
} >> ./RUN
