MACHINE="wcoss2"
MACHINETYPE="backup"
version="v1.0.1"
ACCOUNT="RRFS_DEV"
EXPT_SUBDIR="rrfs_conus_enkf_13km.20251029.dev-sci"
EXPT_BASEDIR="/lfs/h2/emc/da/noscrub/donald.e.lippi/RRFSv1/expt_dirs/July2025_retro/$version/"

PREDEF_GRID_NAME=RRFS_CONUS_13km

. set_rrfs_config_general.sh

HPSS_ACCOUNT="RRFS-DEV"
QUEUE_DEFAULT="dev"
QUEUE_HPSS="dev_transfer"
QUEUE_FCST="dev"
QUEUE_POST="dev"
QUEUE_PRDGEN="dev"
QUEUE_ANALYSIS="dev"
QUEUE_GRAPHICS="dev"

DO_ENSEMBLE="TRUE"
#DO_ENSFCST="TRUE"
#DO_DACYCLE="TRUE"
#DO_SURFACE_CYCLE="TRUE"
DO_SPINUP="TRUE"
DO_SAVE_DA_OUTPUT="TRUE"
DO_POST_SPINUP="FALSE"
DO_POST_PROD="FALSE"
DO_RETRO="TRUE"
DO_NONVAR_CLDANAL="TRUE"
#DO_ENVAR_RADAR_REF="TRUE"
DO_SMOKE_DUST="FALSE"
DO_PM_DA="FALSE"
#DO_REFL2TTEN="FALSE"
#RADARREFL_TIMELEVEL=(0)
#FH_DFI_RADAR="0.0,0.25,0.5"
#DO_SOIL_ADJUST="TRUE"
#DO_RADDA="FALSE"
#DO_BUFRSND="TRUE"
#USE_FVCOM="TRUE"
#PREP_FVCOM="TRUE"
DO_GLM_FED_DA="TRUE"
GLMFED_DATA_MODE="FULL"
PREP_MODEL_FOR_FED="TRUE"
USE_CLM="TRUE"
DO_PARALLEL_PRDGEN="TRUE"
DO_GSIDIAG_OFFLINE="FALSE"

# Options for blending or cold2warm start conversion.
DO_ENS_BLENDING="TRUE"
if [[ ${DO_ENS_BLENDING} == "TRUE" ]] ; then
  ENS_BLENDING_LENGTHSCALE=960
  BLEND="TRUE"          # TRUE:  Blend RRFS and GDAS EnKF
                      # FALSE: Don't blend, activate cold2warm start only, and use either GDAS or RRFS
  USE_HOST_ENKF="TRUE"  # TRUE:  Final EnKF (u,v,t,delp,sphum) will be GDAS (no blending)
                      # FALSE: Final EnKF (u,v,t,delp,sphum) will be RRFS (no blending)
fi

if [[ ${DO_ENSFCST} == "TRUE" ]] ; then
  EXPT_SUBDIR="rrfs_c_enfcst"
  DO_SPINUP="FALSE"
  DO_SAVE_DA_OUTPUT="TRUE"
  DO_NONVAR_CLDANAL="FALSE"
  DO_POST_PROD="TRUE"
  DO_BUFRSND="TRUE"
fi

EXTRN_MDL_ICS_OFFSET_HRS="6"
LBC_SPEC_INTVL_HRS="1"
EXTRN_MDL_LBCS_OFFSET_HRS="6"
BOUNDARY_LEN_HRS="12"
BOUNDARY_PROC_GROUP_NUM="4"

# avaialble retro period:
# 20210511-20210531; 20210718-20210801
DATE_FIRST_CYCL="20250706"
DATE_LAST_CYCL="20250707"
CYCL_HRS=( "00" "12" )
CYCL_HRS=( "18" )
CYCL_HRS_SPINSTART=("06" "18")
CYCL_HRS_PRODSTART=("07" "19")
if [[ ${DO_ENSFCST} == "TRUE" ]] ; then
  CYCL_HRS_STOCH=("00" "06" "12" "18")
fi
#CYCL_HRS_RECENTER=("19")
CYCLEMONTH="07"
CYCLEDAY="06-07"

STARTYEAR=${DATE_FIRST_CYCL:0:4}
STARTMONTH=${DATE_FIRST_CYCL:4:2}
STARTDAY=${DATE_FIRST_CYCL:6:2}
STARTHOUR="00"
ENDYEAR=${DATE_LAST_CYCL:0:4}
ENDMONTH=${DATE_LAST_CYCL:4:2}
ENDDAY=${DATE_LAST_CYCL:6:2}
ENDHOUR="23"

PREEXISTING_DIR_METHOD="upgrade" # "rename"
INITIAL_CYCLEDEF="${DATE_FIRST_CYCL}0600 ${DATE_LAST_CYCL}2300 12:00:00"
BOUNDARY_CYCLEDEF="${DATE_FIRST_CYCL}0600 ${DATE_LAST_CYCL}2300 06:00:00"
PROD_CYCLEDEF="${DATE_FIRST_CYCL}0000 ${DATE_LAST_CYCL}2300 01:00:00"
PRODLONG_CYCLEDEF="00 01 01 01 2100 *"
#RECENTER_CYCLEDEF="00 19 * 10 2022 *"
#ARCHIVE_CYCLEDEF="${DATE_FIRST_CYCL}1400 ${DATE_LAST_CYCL}2300 24:00:00"
if [[ ${DO_ENSFCST} == "TRUE" ]] ; then
  BOUNDARY_LEN_HRS="60"
  LBC_SPEC_INTVL_HRS="3"
  DO_SPINUP="FALSE"
  INITIAL_CYCLEDEF="00 01 01 01 2100 *"
  BOUNDARY_CYCLEDEF="${DATE_FIRST_CYCL}0000 ${DATE_LAST_CYCL}2300 06:00:00"
  PROD_CYCLEDEF="${DATE_FIRST_CYCL}0000 ${DATE_LAST_CYCL}2300 06:00:00"
  RECENTER_CYCLEDEF="${DATE_FIRST_CYCL}0000 ${DATE_LAST_CYCL}2300 06:00:00"
fi
if [[ $DO_SPINUP == "TRUE" ]] ; then
  SPINUP_CYCLEDEF="${DATE_FIRST_CYCL}0600 ${DATE_LAST_CYCL}2300 12:00:00"
fi
if [[ $DO_SAVE_DA_OUTPUT == "TRUE" ]] ; then
  SAVEDA_CYCLEDEF="${DATE_FIRST_CYCL}0000 ${DATE_LAST_CYCL}2300 06:00:00"
fi

FCST_LEN_HRS="1"
FCST_LEN_HRS_SPINUP="1"
POSTPROC_LEN_HRS="1"
#FCST_LEN_HRS_CYCLES=(48 18 18 18 18 18 48 18 18 18 18 18 48 18 18 18 18 18 48 18 18 18 18 18)
for i in {0..23}; do FCST_LEN_HRS_CYCLES[$i]=1; done
for i in {0..23..6}; do FCST_LEN_HRS_CYCLES[$i]=1; done
if [[ ${DO_ENSFCST} == "TRUE" ]] ; then
  for i in {0..23..06}; do FCST_LEN_HRS_CYCLES[$i]=60; done
  FCST_LEN_HRS="60"
  POSTPROC_LEN_HRS="60"
  BOUNDARY_PROC_GROUP_NUM="10"
fi
DA_CYCLE_INTERV="1"
RESTART_INTERVAL="1"
RESTART_INTERVAL_LONG="1"
netcdf_diag=.true.
binary_diag=.false.
WRTCMP_output_file="netcdf_parallel"
WRTCMP_ideflate="1"
WRTCMP_quantize_nsd="18"

## set up post
OUTPUT_FH="1 -1"

WTIME_RUN_FCST="00:30:00"
WTIME_RUN_FCST_LONG="04:45:00"
PPN_RUN_ANALYSIS="16"
NNODES_RUN_ANALYSIS="1"
TPP_RUN_ANALYSIS="8"

EXTRN_MDL_NAME_ICS="GDASENKF"
FV3GFS_FILE_FMT_ICS="netcdf"
EXTRN_MDL_NAME_LBCS="GEFS"
FV3GFS_FILE_FMT_LBCS="grib2"
EXTRN_MDL_SAVETYPE="GSL"

envir="para"
NET="rrfs_a"
ARCHIVEDIR="/NCEPDEV/emc-meso/1year/emc.lam"
NCL_REGION="c"
MODEL="RRFS_A"

if [[ ${DO_ENSEMBLE}  == "TRUE" ]]; then
   NUM_ENS_MEMBERS=30
#   DO_ENSCONTROL="TRUE"
   DO_GSIOBSERVER="TRUE"
   DO_ENKFUPDATE="TRUE"
#   DO_RECENTER="TRUE"
   DO_ENS_GRAPHICS="FALSE"
   #DO_ENKF_RADAR_REF="TRUE"
   DO_ENSPOST="FALSE"
   DO_ENSINIT="TRUE"

   RADAR_REF_THINNING="2"
   ARCHIVEDIR="/5year/BMC/wrfruc/rrfs_ens"
   CLEAN_OLDFCST_HRS="12"
   CLEAN_OLDSTMPPOST_HRS="12"
   cld_bld_hgt=0.0
   l_precip_clear_only=.true.
   write_diag_2=.true.

   if [[ $PREDEF_GRID_NAME == "RRFS_CONUS_13km" ]]; then
     PPN_RUN_RECENTER="128"
     NNODES_RUN_RECENTER="1"
   elif [[ $PREDEF_GRID_NAME == "RRFS_NA_3km" ]]; then
     START_TIME_SPINUP="00:30:00"
     LAYOUT_X="50"
     LAYOUT_Y="64"
     NNODES_RUN_FCST="52"
     WRTCMP_write_tasks_per_group="128"
     PPN_RUN_RECENTER="128"
     NNODES_RUN_RECENTER="10"
   fi

   NUM_ENS_MEMBERS_FCST=5
   if [[ ${DO_ENSFCST} == "TRUE" ]] ; then
     NUM_ENS_MEMBERS=${NUM_ENS_MEMBERS_FCST}
     WTIME_RUN_FCST="04:45:00"
     WTIME_MAKE_LBCS="01:30:00"

     LAYOUT_X="50"
     LAYOUT_Y="64"
     NNODES_RUN_FCST="52"
     WRTCMP_write_groups="1"
     WRTCMP_write_tasks_per_group="128"

     DO_ENSFCST_MULPHY="TRUE"
     DO_SPP="TRUE"
     DO_SPPT="FALSE"
     DO_SKEB="FALSE"
     SPPT_MAG="0.5"
     DO_LSM_SPP="TRUE"
     DO_RECENTER="TRUE"

   fi
fi

SPPINT=36
LNDPINT=180

RUN_ensctrl="rrfs"
RUN="enkfrrfs"
TAG="c13enkf101"
if [[ ${DO_ENSFCST} == "TRUE" ]] ; then
  RUN="refs"
  TAG="c13enfcst101"
fi
COMINgfs=""

. set_rrfs_config.sh

STMP="/lfs/h2/emc/stmp/$USER/July2025_retro/$version/$EXPT_SUBDIR"
PTMP="/lfs/h2/emc/ptmp/$USER/July2025_retro/$version/$EXPT_SUBDIR"
NWGES="/lfs/h2/emc/ptmp/$USER/July2025_retro/$version/$EXPT_SUBDIR/nwges"
if [[ ${DO_ENSFCST} == "TRUE" ]] ; then
  STMP="/lfs/h2/emc/stmp/$USER/July2025_retro/$version/$EXPT_SUBDIR/ensfcst"
  PTMP="/lfs/h2/emc/ptmp/$USER/July2025_retro/$version/$EXPT_SUBDIR/ensfcst"
  NWGES="$NWGES"
fi
ENSCTRL_STMP="/lfs/h2/emc/stmp/$USER/July2025_retro/$version/rrfs_conus_13km.20251029.dev-sci"
ENSCTRL_PTMP="/lfs/h2/emc/ptmp/$USER/July2025_retro/$version/rrfs_conus_13km.20251029.dev-sci"
ENSCTRL_NWGES="/lfs/h2/emc/ptmp/$USER/July2025_retro/$version/rrfs_conus_13km.20251029.dev-sci/nwges"
