whatis("Description: RRFS build environment common libraries")

help([[Load RRFS Model common libraries]])

load(pathJoin("jasper", os.getenv("jasper_ver") or "2.0.32"))
load(pathJoin("libpng", os.getenv("libpng_ver") or "1.6.37"))
load(pathJoin("hdf5", os.getenv("hdf5_ver") or "1.14.3"))
load(pathJoin("netcdf-c", os.getenv("netcdf-c_ver") or "4.9.2"))
load(pathJoin("netcdf-fortran", os.getenv("netcdf-fortran_ver") or "4.6.1"))
load(pathJoin("parallelio", os.getenv("pio_ver") or "2.6.2"))
load(pathJoin("esmf", os.getenv("esmf_ver") or "8.8.0"))
load(pathJoin("fms", os.getenv("fms_ver") or "2024.02"))

load(pathJoin("bacio", os.getenv("bacio_ver") or "2.4.1"))
load(pathJoin("crtm", os.getenv("crtm_ver") or "2.4.0.1"))
load(pathJoin("g2", os.getenv("g2_ver") or "3.5.1"))
load(pathJoin("g2tmpl", os.getenv("g2tmpl_ver") or "1.13.0"))
load(pathJoin("ip", os.getenv("ip_ver") or "5.1.0"))
load(pathJoin("sp", os.getenv("sp_ver") or "2.5.0"))

load(pathJoin("w3emc", os.getenv("w3emc_ver") or "2.10.0"))
load(pathJoin("gftl-shared", os.getenv("gftl-shared_ver") or "1.9.0"))
load(pathJoin("mapl", os.getenv("mapl_ver") or "2.53.4-esmf-8.8.0"))
load(pathJoin("scotch", os.getenv("scotch_ver") or "7.0.4"))
load(pathJoin("zlib", os.getenv("zlib_ver") or "1.2.13"))

load(pathJoin("bufr", os.getenv("bufr_ver") or "12.1.0"))
load(pathJoin("sigio", os.getenv("sigio_ver") or "2.3.3"))
load(pathJoin("sfcio", os.getenv("sfcio_ver") or "1.4.2"))
load(pathJoin("nemsio", os.getenv("nemsio_ver") or "2.5.4"))
load(pathJoin("wrf-io", os.getenv("wrf_io_ver") or "1.2.0"))
load(pathJoin("ncio", os.getenv("ncio_ver") or "1.1.2"))
load(pathJoin("gsi-ncdiag", os.getenv("gsi-ncdiag_ver") or "1.1.2"))
load(pathJoin("w3nco", os.getenv("w3nco_ver") or "2.4.1"))

load(pathJoin("nco", os.getenv("nco_ver") or "5.2.4"))
load(pathJoin("prod_util", os.getenv("prod_util_ver") or "2.1.1"))
load(pathJoin("wgrib2", os.getenv("wgrib2_ver") or "3.6.0"))
