#!/bin/bash

#-----------------------------------------------------------------------
#
# This J-JOB script runs the standalone JEDI EnVAR IODA task
#      for the FV3-LAM model
#
#-----------------------------------------------------------------------

#
#-----------------------------------------------------------------------
#
# Source the variable definitions file and the bash utility functions.
#
#-----------------------------------------------------------------------
#
. ${GLOBAL_VAR_DEFNS_FP}
. $USHDIR/source_util_funcs.sh
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; set -u +x; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs a standalone JEDI EnVAR
IODA task with FV3 for the specified cycle.
========================================================================"
#
#-----------------------------------------------------------------------
#
# Creating COMOUT folders for the task
#
#-----------------------------------------------------------------------
#

if [ "${RUN_ENVIR}" = "nco" ]; then
  COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/$cyc${SLASH_ENSMEM_SUBDIR}"
  if [ ${CYCLE_TYPE} == "spinup" ]; then
    COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/${cyc}_spinup${SLASH_ENSMEM_SUBDIR}"
  fi
  mkdir_vrfy -p "${COMOUT}"
fi

#
#-----------------------------------------------------------------------
#
# Create the working directory under the cycle directory.
#
#-----------------------------------------------------------------------
#
if [ ${CYCLE_TYPE} == "spinup" ]; then
  analworkname="jedienvar_ioda_spinup"
else
  analworkname="jedienvar_ioda"
fi

if [ ${MEM_TYPE} == "MEAN" ]; then
  workdir="${CYCLE_DIR}/ensmean/${analworkname}"
  SLASH_ENSMEM_SUBDIR=""
else
  workdir="${CYCLE_DIR}${SLASH_ENSMEM_SUBDIR}/${analworkname}"
fi
rm -fr ${workdir}
mkdir_vrfy -p ${workdir}
#
#-----------------------------------------------------------------------
#
# Call the ex-script for this J-job and pass to it the necessary varia-
# bles.
#
#-----------------------------------------------------------------------
# 
$SCRIPTSDIR/exregional_jedienvar_ioda.sh \
             cycle_dir="${CYCLE_DIR}" \
             cycle_type="${CYCLE_TYPE}" \
             mem_type="${MEM_TYPE}" \
             workdir="${workdir}"  \
             slash_ensmem_subdir="${SLASH_ENSMEM_SUBDIR}" \
			 comout="${COMOUT}" || \
print_err_msg_exit "\
Call to ex-script corresponding to J-job \"${scrfunc_fn}\" failed."
#
#-----------------------------------------------------------------------
#
# Print exit message.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/func-
# tion.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

