#!/bin/bash


#
#-----------------------------------------------------------------------
#
# This J-JOB script runs the GLM gridded lightning data preprocess 
#      for the FV3-LAM model
#
#-----------------------------------------------------------------------
#

#
#-----------------------------------------------------------------------
#
# Source the variable definitions file and the bash utility functions.
#
#-----------------------------------------------------------------------
#
. ${GLOBAL_VAR_DEFNS_FP}
. $USHdir/source_util_funcs.sh
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; set -u +x; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs a GLM FED 
preprocess with FV3 for the specified cycle.
========================================================================"
#
#-----------------------------------------------------------------------
#
# Create the working directory under the cycle directory.
#
#-----------------------------------------------------------------------
#
if [ ${CYCLE_TYPE} == "spinup" ]; then
  workdir=${CYCLE_DIR}/process_glmfed_spinup
else
  workdir=${CYCLE_DIR}/process_glmfed
fi
if [ ${IS_ENSEMBLE} == "1" ]; then
  workdir=${CYCLE_DIR}/process_glmfed_enkf
fi

rm -fr ${workdir}
mkdir_vrfy -p ${workdir}

cd ${workdir}

export FIX_GSI=$FIX_GSI
export OBS_EAST=$GLMFED_EAST_ROOT
export OBS_WEST=$GLMFED_WEST_ROOT
export RRFSE_NWGES_BASEDIR=$RRFSE_NWGES_BASEDIR
export NUM_ENS_MEMBERS=$NUM_ENS_MEMBERS
export DA_CYCLE_INTERV=$DA_CYCLE_INTERV
export MODE=$GLMFED_DATA_MODE
#
#-----------------------------------------------------------------------
#
# Call the ex-script for this J-job and pass to it the necessary varia-
# bles.
#
#-----------------------------------------------------------------------
#
python -u ${SCRIPTSdir}/exrrfs_prep_glmfed.py \
#
#-----------------------------------------------------------------------
#
#-----------------------------------------------------------------------
#
# Print exit message.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/func-
# tion.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

