#!/bin/bash

date
export PS4=' $SECONDS + '
set -xue

#-----------------------------------------------------------------------
# Source the variable definitions file and the bash utility functions.
#-----------------------------------------------------------------------
export USHrrfs=${USHrrfs:-${HOMErrfs}/ush}
export PARMrrfs=${PARMrrfs:-${HOMErrfs}/parm}
export EXECrrfs=${EXECrrfs:-${HOMErrfs}/exec}
export FIXrrfs=${FIXrrfs:-${HOMErrfs}/fix}

export DATAROOT="${DATAROOT:-${DATAROOT_dfv}}"
export umbrella_data=${DATAROOT}/${RUN}_${PDY}${cyc}
export DATA=${DATA:-${umbrella_data}/${jobid}}

mkdir -p ${DATA}
cd ${DATA}
. ${GLOBAL_VAR_DEFNS_FP}
. $USHrrfs/source_util_funcs.sh
export cycle="t${cyc}z"
setpdy.sh
. ./PDY
export CDATE=${PDY}${cyc}

${HOMErrfs}/scripts/exrrfs_fsm.sh
export err=$?; err_chk

if [ "${KEEPDATA}" != "YES" ]; then
  rm -rf ${DATA}
fi
