#!/bin/bash

#
#-----------------------------------------------------------------------
#
# This script runs the pygraf create_graphics driver for creating
# PNG figures and zipping them for dissemination to the web.
#
#-----------------------------------------------------------------------
#

#
#-----------------------------------------------------------------------
#
# Source the variable definitions file and the bash utility functions.
#
#-----------------------------------------------------------------------
#
. ${GLOBAL_VAR_DEFNS_FP}
. $USHdir/source_util_funcs.sh

date
export PS4='+ $SECONDS + '
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; set -u -x; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs the post-processor (UPP)
on the output files corresponding to a specified forecast hour.
========================================================================"
#
#-----------------------------------------------------------------------
#
# Set the run directory and post directories.
#
#-----------------------------------------------------------------------
#
COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/$cyc${SLASH_ENSMEM_SUBDIR}"
COMOUT_mem0="${ENSCTRL_COMOUT_BASEDIR}/${RUN_ensctrl}.$PDY/$cyc"
postprd_dir="${COMOUT}/${ENSPROD:-}"
run_dir="${COMOUT}/pyprd"
zip_dir="${COMOUT}/nclprd"

if [ "${IS_RTMA}" = "TRUE" ]; then
  fcst_length=${FCST_LEN_HRS_CYCLES[$((10#$cyc))]/%.*/}
else
  fcst_length=${FCST_LEN_HRS_CYCLES[$((10#$cyc))]}
fi

IMAGES_FN=${IMAGES_FN:-$PYTHON_GRAPHICS_YML_FN}
# Choose an appropriate sites file for the grid
sites_file=conus_raobs.txt
tiles=${TILES:-full}

if [[ "${PREDEF_GRID_NAME}" =~ "AK" || \
      "${TILELABEL:-}" == "242" || \
      "${TILELABEL:-}" == "hrrrak" ]] ; then
  sites_file=alaska_raobs.txt
  tiles=${TILES:-hrrrak}

elif [[ "${PREDEF_GRID_NAME}" =~ "RAP" || \
        "${PREDEF_GRID_NAME}" =~ "NA" || \
        "${TILELABEL:-}" = "221" ]] ; then
  age=5
  wait_time=15
  sites_file=na_raobs.txt
  tiles=${TILES:-full}

elif [[ "${TILELABEL:-}" = hrrr ]] ; then

  # This domain comes from a NA domain, so wait longer.
  age=5
  wait_time=15
  tiles=${TILES:-hrrr}

fi

# Use a subdirectory for input from alternative wgrib2-produced grids.
wgrib2_grids=( hrrr hrrrak full )
first_grid=${tiles%%,*} # First in a comma separated list
first_grid=${first_grid%%_*} # First part of an underscore separated string (requirement set by Rocoto)

sub_conus_grids=( SE SC SW NE NC NW \
  ATL CA-NV CentralCA CHI-DET DCArea EastCO GreatLakes NYC-BOS SEA-POR SouthCA SouthFL VortexSE )

sub_ak_grids=( AKRange Anchorage Juneau )

if [[ "${sub_conus_grids[*]}" =~ $first_grid ]] ; then
  subdir=hrrr_grid
elif [[ "${sub_ak_grids[*]}" =~ $first_grid ]] ; then
  subdir=hrrrak_grid
elif [[ "${wgrib2_grids[*]}" =~ $first_grid ]] ; then
  subdir=${first_grid:-}_grid
fi

if [ -d ${postprd_dir}/${subdir} ] ; then
  postprd_dir=${postprd_dir}/${subdir}
  run_dir=${run_dir}/${subdir:-}
  zip_dir=${zip_dir}/${subdir:-}
fi

if [ "${ENSPROD:-}" = 'ensprod' ] ; then
  file_id="ens"
  start_hour=1
fi

# Choose the appropriate file template for graphics type
net4=$(echo ${NET:0:4} | tr '[:upper:]' '[:lower:]')
if [ ${PREDEF_GRID_NAME} = "RRFS_CONUS_3km" ]; then
  gridname="conus_3km."
elif  [ ${PREDEF_GRID_NAME} = "RRFS_NA_3km" ]; then
  gridname=""
fi

case ${GRAPHICS_TYPE} in

  "maps")

    file_tmpl="${net4}.t${CDATE:8:2}z.prslev.f{FCST_TIME:03d}.${gridname}grib2"
    file_type=prs
    extra_args="\
      --tiles $tiles \
      --images ${PYTHON_GRAPHICS_DIR}/image_lists/${IMAGES_FN} hourly"
    if [ ${ALL_LEADS:-true} = "true" ] ; then
        extra_args="\
          ${extra_args} \
          --all_leads"
    fi
    ;;

  "skewts")

    file_tmpl="${net4}.t${CDATE:8:2}z.natlev.f{FCST_TIME:03d}.${gridname}grib2"
    file_type=nat
    extra_args="\
      --sites ${PYTHON_GRAPHICS_DIR}/static/${sites_file} \
      --max_plev 100"
    ;;

  "enspanel")

    file_tmpl="${net4}.t${CDATE:8:2}z.prslev.f{FCST_TIME:03d}.${gridname}grib2"
    file_type=prs
    extra_args="\
      --tiles $tiles \
      --images ${PYTHON_GRAPHICS_DIR}/image_lists/rrfs_ens.yml hourly"

    # Link in control member to the location it should be
    ens_mem0=${postprd_dir/'#mem#'/'0000'/}
    mem0_fp=${COMOUT_mem0}
    mem0_fn=${file_tmpl/'{FCST_TIME:03d}'/'*'}

    mkdir -p ${ens_mem0}
    pushd ${ens_mem0}

    rm *.grib2

    for mem0_file in $( find ${mem0_fp} -name ${mem0_fn} ) ; do
      cp ${mem0_file} .
    done
    popd

    # Create a python template for postprd_dir
    postprd_dir=${postprd_dir/'#mem#'/'{mem:04d}'/}

    # Remove ensemble reference from output locations
    run_dir=${run_dir/'/mem#mem#/'//}
    zip_dir=${zip_dir/'/mem#mem#/'//}

    ;;

  *)
    err_exit "\
      GRAPHICS_TYPE \"${GRAPHICS_TYPE}\" is not recognized."
    ;;
esac
mkdir -p "${run_dir}"
#
#-----------------------------------------------------------------------
#
# Call the graphics driver script.
#
#-----------------------------------------------------------------------
#
cd ${PYTHON_GRAPHICS_DIR}
python -u ${PYTHON_GRAPHICS_DIR}/create_graphics.py \
  ${GRAPHICS_TYPE} \
  -a ${age:-3} \
  -d ${postprd_dir} \
  -f ${start_hour:-0} ${fcst_length} \
  --file_tmpl ${file_tmpl} \
  --file_type ${file_type} \
  -m "${MODEL}" \
  -n ${SLURM_CPUS_ON_NODE:-12} \
  -o ${run_dir} \
  -s ${CDATE} \
  -w ${wait_time:-30} \
  -z ${zip_dir} \
  ${extra_args}
export err=$?; err_chk
#
#-----------------------------------------------------------------------
#
# Print exit message.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/function.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

