#!/bin/bash

#-----------------------------------------------------------------------
# RRFS Post Analysis
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Source the variable definitions file and the bash utility functions.
#-----------------------------------------------------------------------

. ${GLOBAL_VAR_DEFNS_FP}
. $USHdir/source_util_funcs.sh

date
export PS4='+ $SECONDS + '

#-----------------------------------------------------------------------
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#-----------------------------------------------------------------------

{ save_shell_opts; set -u -x; } > /dev/null 2>&1

#-----------------------------------------------------------------------
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#-----------------------------------------------------------------------

scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )

#-----------------------------------------------------------------------
# Print message indicating entry into script.
#-----------------------------------------------------------------------

print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs the applications after
analysis with RRFS for the specified cycle.
========================================================================"

#-----------------------------------------------------------------------
# Obtain unique process id (pid) and create the run directory (DATA).
#-----------------------------------------------------------------------

export pid=${pid:-$$}
export envir=${envir:-prod}
export RUN=${RUN:-rrfs}

export mem_num=m$(echo "${ENSMEM_INDX}")
export CYCLE_TYPE=${CYCLE_TYPE:-prod}

if [ "${CYCLE_TYPE}" = "spinup" ]; then
  workname="gsi_spinup"
else
  workname="gsi"
fi

if [[ ! -v OB_TYPE ]]; then
  OB_TYPE="conv"
fi
if [ "${GSI_TYPE}" = "OBSERVER" ]; then
  if [ "${MEM_TYPE}" = "MEAN" ]; then
    export jobid=${RUN}_observer_${workname}_ensmean_${envir}_${cyc}
  else
    export jobid=${RUN}_observer_${workname}_${mem_num}_${envir}_${cyc}
  fi
else
  export jobid=${RUN}_analysis_${OB_TYPE}_${workname}_${envir}_${cyc}
fi

export DATA=${DATAROOT}/${jobid}

if [[ ! -d ${DATA} ]]; then
  echo "cannot find analysis run directory"
  exit 
fi
cd ${DATA}

#  directory has grid_spec files for restart subdomains
export gridspec_dir=${GESROOT}/grid_spec

export ${OB_TYPE}

#-----------------------------------------------------------------------
# Define COM directories
#-----------------------------------------------------------------------

if [ "${CYCLE_TYPE}" = "spinup" ]; then
  if [ "${DO_ENSEMBLE}" = "TRUE" ]; then
    export COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/${cyc}_spinup/${mem_num}"
  else
    export COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/${cyc}_spinup"
  fi
else
  if [ "${MEM_TYPE}" = "MEAN" ]; then
    export COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/$cyc/ensmean"
  else
    if [ "${DO_ENSEMBLE}" = "TRUE" ]; then
      export COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/${cyc}/${mem_num}"
    else
      export COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/${cyc}"
    fi
  fi
fi
mkdir -p "${COMOUT}"

#-----------------------------------------------------------------------
# Execute the script.
#-----------------------------------------------------------------------

export pgmout="${DATA}/OUTPUT.$$"
env

$SCRIPTSdir/exrrfs_run_postanal.sh
export err=$?; err_chk

if [ -e "$pgmout" ]; then
  cat $pgmout
fi

if [ "${KEEPDATA}" = "NO" ]; then
  rm -rf ${DATA}
fi

#-----------------------------------------------------------------------
# Print exit message.
#-----------------------------------------------------------------------

print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"

#-----------------------------------------------------------------------
# Restore the shell options saved at the beginning of this script/function.
#-----------------------------------------------------------------------

{ restore_shell_opts; } > /dev/null 2>&1

