#!/bin/bash

date
export PS4='+ $SECONDS + ' 
set -xue

#-----------------------------------------------------------------------
# Specify Package Location
#-----------------------------------------------------------------------
export NET='rrfs'
export MACHINE="WCOSS2"
export WORKFLOW_MANAGER="ecflow"
export HOMErrfs=${HOMErrfs:-""}
export EXECrrfs=${EXECrrfs:-${HOMErrfs}/exec}
export FIXrrfs=${FIXrrfs:-${HOMErrfs}/fix}
export PARMrrfs=${PARMrrfs:-${HOMErrfs}/parm}
export USHrrfs=${USHrrfs:-${HOMErrfs}/ush}
export FIX_SMOKE_DUST="${FIXrrfs}/smoke_dust"
export FIRE_RAVE_DIR="${DCOMROOT}"
#-----------------------------------------------------------------------
# RRFS Smoke Preprocessing
#-----------------------------------------------------------------------
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}
case "${WGF}" in
  "det")
    export RUN="rrfs"
    ;;
  "enkf")
    export RUN="enkfrrfs"
    ;;
  "ensf")
    export RUN="refs"
    ;;
  "firewx")
    export RUN="firewx"
    ;;
esac
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p ${DATA}
cd ${DATA}
export cycle="t${cyc}z"
setpdy.sh
. ./PDY
export CDATE="${PDY}${cyc}"


#-----------------------------------------------------------------------
# Source the bash utility functions.
#-----------------------------------------------------------------------

. $USHrrfs/source_util_funcs.sh

#-----------------------------------------------------------------------
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#-----------------------------------------------------------------------

scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )

#-----------------------------------------------------------------------
# Print message indicating entry into script.
#-----------------------------------------------------------------------

print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs the smoke preprocessing
for the specified cycle.
========================================================================"

#-----------------------------------------------------------------------
# Define COM directories
#-----------------------------------------------------------------------

export COMrrfs=${COMrrfs:-$(compath.py -o ${NET}/${rrfs_ver})}

export COMOUT_HWP=${COMrrfs}/HOURLY_HWP/hourly_hwp.${PDY}
export COMOUT_HWP_1day=${COMrrfs}/HOURLY_HWP/hourly_hwp.${PDYm1}
export COMOUT_HWP_2day=${COMrrfs}/HOURLY_HWP/hourly_hwp.${PDYm2}

export COMOUT_RAVE=${COMrrfs}/RAVE_INTP/rave_intp.${PDY}
export COMOUT_RAVE_1day=${COMrrfs}/RAVE_INTP/rave_intp.${PDYm1}
export COMOUT_RAVE_2day=${COMrrfs}/RAVE_INTP/rave_intp.${PDYm2}

mkdir -p ${COMOUT_HWP}
mkdir -p ${COMOUT_HWP_1day}
mkdir -p ${COMOUT_HWP_2day}

mkdir -p ${COMOUT_RAVE}
mkdir -p ${COMOUT_RAVE_1day}
mkdir -p ${COMOUT_RAVE_2day}

#-----------------------------------------------------------------------
# Execute the script.
#-----------------------------------------------------------------------

export pgmout="${DATA}/OUTPUT.$$"
env

${HOMErrfs}/scripts/exrrfs_process_smoke.sh
export err=$?; err_chk

if [ -e "$pgmout" ]; then
  cat $pgmout
fi

#-----------------------------------------------------------------------
# Print exit message.
#-----------------------------------------------------------------------

print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
