#!/bin/bash

date
export PS4='+ $SECONDS + ' 
set -xue

#-----------------------------------------------------------------------
# RRFS Analysis
#-----------------------------------------------------------------------
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}
export RUN=${RUN:-rrfs}
export MEM_TYPE=${MEM_TYPE:-"MEAN"}

if [ $WGF = "enkf" ] || [ $WGF = "ensf" ]; then
  export GSI_TYPE=${GSI_TYPE:-"OBSERVER"}
  if [ "${MEM_TYPE}" = "MEAN" ]; then
    export ENSMEM_INDX=""
    export mem_num=""
  else
    export ENSMEM_INDX=${MEMBER_NAME}
    export mem_num=m$(echo "${ENSMEM_INDX}")
  fi
  export DO_ENSEMBLE="TRUE"
else
  export ENSMEM_INDX=""
  export mem_num=""
  export DO_ENSEMBLE="FALSE"
fi

export CYCLE_TYPE=${CYCLE_TYPE:-prod}
export COMrrfs=${COMrrfs:-$(compath.py -o ${NET}/${rrfs_ver})}
if [ "${CYCLE_TYPE}" = "spinup" ]; then
  export umbrella_analysis_data=${umbrella_analysis_data:-${DATAROOT}/rrfs_analysis_gsi_spinup_${cyc}_${rrfs_ver}/${WGF}}
  export umbrella_init_data=${umbrella_init_data:-${DATAROOT}/${RUN}_init_spinup_${cyc}_${rrfs_ver}/${WGF}}
  if [ "${DO_ENSEMBLE}" = "TRUE" ]; then
    if [ "${MEM_TYPE}" = "MEAN" ]; then
      export umbrella_forecast_data=${DATAROOT}/rrfs_forecast_spinup_${cyc}_${rrfs_ver}/${WGF}/ensmean
      export COMOUT=${COMrrfs}/enkfrrfs.${PDY}/${cyc}_spinup/ensmean/analysis
      export shared_output_data=${umbrella_analysis_data}/output/ensmean
    else
      export umbrella_forecast_data=${DATAROOT}/rrfs_forecast_spinup_${cyc}_${rrfs_ver}/${WGF}/${mem_num}
      export COMOUT=${COMrrfs}/enkfrrfs.${PDY}/${cyc}_spinup/${mem_num}/analysis
      export shared_output_data=${umbrella_analysis_data}/output/${mem_num}
    fi
  else
    export umbrella_forecast_data=${DATAROOT}/rrfs_forecast_spinup_${cyc}_${rrfs_ver}/${WGF}
    export COMOUT=${COMrrfs}/${RUN}.${PDY}/${cyc}_spinup/analysis
    export shared_output_data=${umbrella_analysis_data}/output
  fi
else
  export umbrella_analysis_data=${umbrella_analysis_data:-${DATAROOT}/rrfs_analysis_gsi_${cyc}_${rrfs_ver}/${WGF}}
  export umbrella_init_data=${umbrella_init_data:-${DATAROOT}/${RUN}_init_${cyc}_${rrfs_ver}/${WGF}}
  if [ "${MEM_TYPE}" = "MEAN" ]; then
    export umbrella_forecast_data=${DATAROOT}/rrfs_forecast_${cyc}_${rrfs_ver}/${WGF}/ensmean
    export COMOUT=${COMrrfs}/enkfrrfs.${PDY}/${cyc}/ensmean/analysis
    export shared_output_data=${umbrella_analysis_data}/output/ensmean
  else
    if [ "${DO_ENSEMBLE}" = "TRUE" ]; then
      export umbrella_forecast_data=${DATAROOT}/rrfs_forecast_${cyc}_${rrfs_ver}/${WGF}/${mem_num}
      export COMOUT=${COMrrfs}/enkfrrfs.${PDY}/${cyc}/${mem_num}/analysis
      export shared_output_data=${umbrella_analysis_data}/output/${mem_num}
    else
      export umbrella_forecast_data=${DATAROOT}/rrfs_forecast_${cyc}_${rrfs_ver}/${WGF}
      export COMOUT=${COMrrfs}/${RUN}.${PDY}/${cyc}/analysis
      export shared_output_data=${umbrella_analysis_data}/output
    fi
  fi
fi 

#-----------------------------------------------------------------------
# Define data directories
#-----------------------------------------------------------------------
#### export shared_output_data=${umbrella_analysis_data}/output
export DATA=${DATA:-${umbrella_analysis_data}/${jobid}}
mkdir -p ${DATA} ${shared_output_data} ${COMOUT}
cd ${DATA}

#-----------------------------------------------------------------------
# Define forecast INPUT directories
#-----------------------------------------------------------------------
export FORECAST_INPUT_PRODUCT=${umbrella_forecast_data}/INPUT
mkdir -p ${FORECAST_INPUT_PRODUCT}
#-----------------------------------------------------------------------
# Source the variable definitions file
#-----------------------------------------------------------------------

. ${HOMErrfs}/ush/rrfs_nco_config.sh

#-----------------------------------------------------------------------
# Specify Execution Areas
#-----------------------------------------------------------------------

export EXECrrfs=${EXECrrfs:-${HOMErrfs}/exec}
export FIXrrfs=${FIXrrfs:-${HOMErrfs}/fix}
export PARMrrfs=${PARMrrfs:-${HOMErrfs}/parm}
export USHrrfs=${USHrrfs:-${HOMErrfs}/ush}
export FIX_GSI=${FIXrrfs}/gsi

#-----------------------------------------------------------------------
# Source the bash utility functions.
#-----------------------------------------------------------------------

. $USHrrfs/source_util_funcs.sh

#-----------------------------------------------------------------------
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#-----------------------------------------------------------------------

{ save_shell_opts; set -u -x; } > /dev/null 2>&1

#-----------------------------------------------------------------------
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#-----------------------------------------------------------------------

scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )

#-----------------------------------------------------------------------
# Print message indicating entry into script.
#-----------------------------------------------------------------------

print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs an analysis with RRFS
for the specified cycle.
========================================================================"

#-----------------------------------------------------------------------
# Execute the script.
#-----------------------------------------------------------------------

export pgmout="${DATA}/OUTPUT.$$"
env

$HOMErrfs/scripts/exrrfs_analysis_gsi.sh
export err=$?; err_chk

if [ -e "$pgmout" ]; then
  cat $pgmout
fi

echo "Analysis GSI job is completed" &> ${umbrella_analysis_data}/analysis_gsi_${CYCLE_TYPE}_clean.flag

if [ "${KEEPDATA}" = "NO" ]; then
  rm -rf ${DATA}
fi

#-----------------------------------------------------------------------
# Print exit message.
#-----------------------------------------------------------------------

print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"

#-----------------------------------------------------------------------
# Restore the shell options saved at the beginning of this script/function.
#-----------------------------------------------------------------------

{ restore_shell_opts; } > /dev/null 2>&1

