#!/bin/bash

#-----------------------------------------------------------------------
#
# This J-JOB script runs the standalone No-Var Cloud Analysis
#
#-----------------------------------------------------------------------

#
#-----------------------------------------------------------------------
#
# Source the variable definitions file and the bash utility functions.
#
#-----------------------------------------------------------------------
#
. ${GLOBAL_VAR_DEFNS_FP}
. $USHdir/source_util_funcs.sh

date
export PS4='+ $SECONDS + '
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; set -u -x; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs a standalone No-Var cloud
analysis with FV3 for the specified cycle.
========================================================================"
#
#-----------------------------------------------------------------------
#
# Create the working directory under the cycle directory.
#
#-----------------------------------------------------------------------
#
if [ "${CYCLE_TYPE}" = "spinup" ]; then
  export analworkname="nonvar_cldanl_spinup"
else
  export analworkname="nonvar_cldanl"
fi
if [ ${MEM_TYPE} = "MEAN" ]; then
  export workdir="${CYCLE_DIR}/ensmean/${analworkname}"
  SLASH_ENSMEM_SUBDIR=""
else
  export workdir="${CYCLE_DIR}${SLASH_ENSMEM_SUBDIR}/${analworkname}"
fi
rm -fr ${workdir}
mkdir -p ${workdir}
cd ${workdir}
#
#  directory has grid_spec files for restart subdomains
#
export gridspec_dir=${NWGES_BASEDIR}/grid_spec
#
#-----------------------------------------------------------------------
#
# create COMOUT/COMIN directory
#
#-----------------------------------------------------------------------
#
if [ ${CYCLE_TYPE} = "spinup" ]; then
  export COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/${cyc}_spinup${SLASH_ENSMEM_SUBDIR}"
  export COMIN="${COMOUT_BASEDIR}/$RUN.$PDY/${cyc}_spinup"
else
  export COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/${cyc}${SLASH_ENSMEM_SUBDIR}"
  export COMIN="${COMOUT_BASEDIR}/$RUN.$PDY/${cyc}"
fi
mkdir -p "${COMOUT}"
#
#-----------------------------------------------------------------------
#
# Call the ex-script for this J-job.
#
#-----------------------------------------------------------------------
#
export pgmout="${workdir}/OUTPUT.$$"
env

$SCRIPTSdir/exrrfs_nonvarcldanl.sh \
             cycle_dir="${CYCLE_DIR}" \
             cycle_type="${CYCLE_TYPE}" \
             mem_type="${MEM_TYPE}" \
             slash_ensmem_subdir="${SLASH_ENSMEM_SUBDIR}"
export err=$?; err_chk

if [ -e "$pgmout" ]; then
  cat $pgmout
fi
#
#-----------------------------------------------------------------------
#
# Print exit message.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/function.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

