#!/usr/bin/env bash
declare -rx PS4='+ $(basename ${BASH_SOURCE[0]:-${FUNCNAME[0]:-"Unknown"}})[${LINENO}]${id}: '
set -x
date
#
#-----------------------------------------------------------------------
# Specify Execution Areas
#-----------------------------------------------------------------------
#
export HOMErrfs=${HOMErrfs} #comes from the workflow at runtime
export EXECrrfs=${EXECrrfs:-${HOMErrfs}/exec}
export FIXrrfs=${FIXrrfs:-${HOMErrfs}/fix}
export PARMrrfs=${PARMrrfs:-${HOMErrfs}/parm}
export USHrrfs=${USHrrfs:-${HOMErrfs}/ush}
#
#-----------------------------------------------------------------------
# Obtain unique process id (pid) and create the run directory (DATA).
#-----------------------------------------------------------------------
#
export pid=${pid:-$$}
if [[ -z "${ENS_INDEX}" ]]; then
  export RUN="rrfs"
else
  export RUN="ensrrfs"
fi
export jobid=${jobid:-${RUN}_ungrib_${TYPE}_${cyc}}
export DATA=${DATA:-${DATAROOT}/${jobid}}

if [ -d ${DATA} ]; then # remove the ${DATA} directory if existed
  rm -rf ${DATA}
fi
mkdir -p ${DATA}

export UMBRELLA_DATA=${UMBRELLA_DATA:-${DATAROOT}/umbrella}
if [ -d ${UMBRELLA_DATA}/ungrib_${TYPE} ]; then
  rm -rf ${UMBRELLA_DATA}/ungrib_${TYPE}
fi
mkdir -p ${UMBRELLA_DATA}/ungrib_${TYPE}

#
#-----------------------------------------------------------------------
# Set the parameters for the external model files.
#-----------------------------------------------------------------------
#
export EXTRN_MDL_SOURCE=${EXTRN_MDL_SOURCE:-"GFS"}
if [[ "${EXTRN_MDL_SOURCE}" == "GFS" ]]; then
  export COMINgfs=${COMINgfs:-$(compath.py $envir/gfs/$gfs_ver)}
elif [[ "${EXTRN_MDL_SOURCE}" == "GEFS" ]]; then
  export COMINgefs=${COMINgefs:-$(compath.py $envir/gefs/$gefs_ver)}
else
  export COMIN=${SOURCE_BASEDIR:-"SOURCE_BASEDIR_not_defined"}
  export NAME_PATTERN=${NAME_PATTERN:-"NAME_PATTERN_not_defined"}
fi
export OFFSET=${OFFSET:-0}
export LENGTH=${LENGTH:-0}
export INTERVAL=${INTERVAL:-1}
#
#-----------------------------------------------------------------------
# Define COM directories
#-----------------------------------------------------------------------
#
COMOUT=${COMOUT:-$(compath.py -o ${NET}/${rrfs_ver}/${RUN}.${PDY}/${cyc})}
if [[ -z "${ENS_INDEX}" ]]; then
  mkdir -p ${COMOUT}/ungrib_${TYPE}
else
  mkdir -p ${COMOUT}/mem${ENS_INDEX}/ungrib_${TYPE}
fi
#
#----------------------------------------
# Execute the script.
#----------------------------------------
#
export pgmout="${DATA}/OUTPUT.$$"
${HOMErrfs}/scripts/exrrfs_ungrib.sh
export err=$?; err_chk

if [ -e "$pgmout" ]; then
  cat $pgmout
fi
#
#----------------------------------------
# Remove the Temporary working directory
#----------------------------------------
#
cd ${DATAROOT}
[[ "${KEEPDATA}" == "NO" ]] && rm -rf ${DATA}
#
date
echo "JOB ${jobid:-} HAS COMPLETED NORMALLY!"
exit 0
