#!/bin/bash

date
export PS4=' $SECONDS + '
set -xue

#-----------------------------------------------------------------------
# RRFS File Service Manager
#-----------------------------------------------------------------------
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p ${DATA}
cd ${DATA}
export WGF=${WGF:-"det"}

#-----------------------------------------------------------------------
# Source the variable definitions file
#-----------------------------------------------------------------------
export USHrrfs=${USHrrfs:-${HOMErrfs}/ush}
export PARMrrfs=${PARMrrfs:-${HOMErrfs}/parm}
export EXECrrfs=${EXECrrfs:-${HOMErrfs}/exec}
export FIXrrfs=${FIXrrfs:-${HOMErrfs}/fix}
export OBSPATH=${OBSPATH:-$(compath.py obsproc/${obsproc_ver})}

#-----------------------------------------------------------------------
# Define COMIN
#-----------------------------------------------------------------------

export COMINgfs=${COMINgfs:-$(compath.py gfs/${gfs_ver})}
export COMINgefs=${COMINgefs:-$(compath.py gefs/${gefs_ver})}
export COMINobsproc="${COMINobsproc:-$(compath.py obsproc/${obsproc_ver})}"

#-----------------------------------------------------------------------
# Source the bash utility functions.
#-----------------------------------------------------------------------

. $USHrrfs/source_util_funcs.sh

export cycle="t${cyc}z"
setpdy.sh
. ./PDY
export CDATE=${PDY}${cyc}

${HOMErrfs}/scripts/exrrfs_fsm.sh
export err=$?; err_chk

exit 0

##################################################
# Remove the Temporary working directory
##################################################
if [ "${KEEPDATA^^}" != YES ]; then
  cd $DATAROOT
  rm -rf $DATA
fi
