#!/usr/bin/env bash
declare -rx PS4='+ $(basename ${BASH_SOURCE[0]:-${FUNCNAME[0]:-"Unknown"}})[${LINENO}]${id}: '
set -x
date
#
#-----------------------------------------------------------------------
# Specify Execution Areas
#-----------------------------------------------------------------------
#
export HOMErrfs=${HOMErrfs} #comes from the workflow at runtime
export EXECrrfs=${EXECrrfs:-${HOMErrfs}/exec}
export FIXrrfs=${FIXrrfs:-${HOMErrfs}/fix}
export PARMrrfs=${PARMrrfs:-${HOMErrfs}/parm}
export USHrrfs=${USHrrfs:-${HOMErrfs}/ush}
#
#-----------------------------------------------------------------------
#  find group and model forecast information
#-----------------------------------------------------------------------
#
export GROUP_INDEX=${GROUP_INDEX:-1}
export GROUP_TOTAL_NUM=${GROUP_TOTAL_NUM:-1}
export HISTORY_INTERVAL=${HISTORY_INTERVAL:-1}
#
#-----------------------------------------------------------------------
# Obtain unique process id (pid) and create the run directory (DATA).
#-----------------------------------------------------------------------
#
export pid=${pid:-$$}
if [[ -z "${ENS_INDEX}" ]]; then
  export MEMID=""
  export MEMDIR=""
else
  export MEMID="_m${ENS_INDEX}"
  export MEMDIR="/m${ENS_INDEX}"
fi
export jobid=${jobid:-${RUN}_mpassit${MEMID}_g${GROUP_INDEX}_${cyc}}

export DATA=${DATA:-${DATAROOT}/${jobid}}
if [ -d ${DATA} ]; then # remove the ${DATA}/${GROUP_INDEX} directory if existed
  rm -rf ${DATA}
fi
mkdir -p ${DATA}

export UMBRELLA_DATA=${UMBRELLA_DATA:-${DATAROOT}/umbrella}
mkdir -p ${UMBRELLA_DATA}/mpassit

#
#-----------------------------------------------------------------------
# Define COM directories
#-----------------------------------------------------------------------
#
export COMINrrfs=${COMINrrfs:-$(compath.py $envir/rrfs/$rrfs_ver)}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${rrfs_ver}/${RUN}.${PDY}/${cyc})}
#
#----------------------------------------
# Execute the script.
#----------------------------------------
export pgmout="${DATA}/OUTPUT.$$"
${HOMErrfs}/scripts/exrrfs_mpassit.sh
export err=$?; err_chk

if [ -e "$pgmout" ]; then
  cat $pgmout
fi
#
#----------------------------------------
# Remove the Temporary working directory
#----------------------------------------
cd ${DATAROOT}
[[ "${KEEPDATA}" == "NO" ]] && rm -rf ${DATA}
#
date
echo "JOB ${jobid:-} HAS COMPLETED NORMALLY!"
exit 0
