#!/usr/bin/env bash
declare -rx PS4='+ $(basename ${BASH_SOURCE[0]:-${FUNCNAME[0]:-"Unknown"}})[${LINENO}]: '
set -x
date

#
#-----------------------------------------------------------------------
# Specify Execution Areas
#-----------------------------------------------------------------------
#
export HOMErrfs=${HOMErrfs} #comes from the workflow at runtime
export EXECrrfs=${EXECrrfs:-${HOMErrfs}/exec}
export FIXrrfs=${FIXrrfs:-${HOMErrfs}/fix}
export PARMrrfs=${PARMrrfs:-${HOMErrfs}/parm}
export USHrrfs=${USHrrfs:-${HOMErrfs}/ush}
#
#-----------------------------------------------------------------------
#  find group  and external model information
#-----------------------------------------------------------------------
#
export GROUP_INDEX=${GROUP_INDEX:-1}
export GROUP_TOTAL_NUM=${GROUP_TOTAL_NUM:-1}
export OFFSET=${OFFSET:-0}
export LENGTH=${LENGTH:-0}
export INTERVAL=${INTERVAL:-1}
#
#-----------------------------------------------------------------------
# Obtain unique process id (pid) and create the run directory (DATA).
#-----------------------------------------------------------------------
#
export pid=${pid:-$$}
if [[ -z "${ENS_INDEX}" ]]; then
  export MEMDIR=""
else
  export MEMDIR="/mem${ENS_INDEX}"
fi
export UMBRELLA_UNGRIB_LBC_DATA=${UMBRELLA_UNGRIB_LBC_DATA:-${DATAROOT}/${RUN}_ungrib_lbc_${cyc}_${rrfs_ver}/${WGF}${MEMDIR}}
export jobid=${jobid:-lbc_g${GROUP_INDEX}_${cyc}}
export UMBRELLA_LBC_DATA=${UMBRELLA_LBC_DATA:-${DATAROOT}/${RUN}_lbc_${cyc}_${rrfs_ver}/${WGF}${MEMDIR}}
export DATA=${DATA:-${UMBRELLA_LBC_DATA}/${jobid}}

if [[ -d "${DATA}" ]]; then # remove the ${DATA} directory if existed
  rm -rf "${DATA}"
fi
mkdir -p "${DATA}"
#
#-----------------------------------------------------------------------
# Define COM directories
#-----------------------------------------------------------------------
#
export COMINrrfs=${COMINrrfs:-$(compath.py "${envir}/rrfs/${rrfs_ver}")}
export COMOUT=${COMOUT:-$(compath.py -o "${NET}/${rrfs_ver}/${RUN}.${PDY}/${cyc}")}
mkdir -p "${COMOUT}/lbc/${WGF}${MEMDIR}"
#
#----------------------------------------
# Execute the script.
#----------------------------------------
export pgmout="${DATA}/OUTPUT.$$"
"${HOMErrfs}"/scripts/exrrfs_lbc.sh
export err=$?; err_chk

if [[ -e "${pgmout}" ]]; then
  cat "${pgmout}"
fi
#
#----------------------------------------
# Remove the Temporary working directory
#----------------------------------------
if [[ "${KEEPDATA^^}" == "NO" ]]; then
  rm -rf "${DATA}"
fi
#
date
echo "JOB ${jobid:-} HAS COMPLETED NORMALLY!"
exit 0
