#!/bin/bash

date
export PS4='+ $SECONDS + '
set -x

export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p ${DATA}
cd ${DATA}

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY

export USHrrfs=${USHrrfs:-${HOMErrfs}/ush}
export PARMrrfs=${PARMrrfs:-${HOMErrfs}/parm}
export EXECrrfs=${EXECrrfs:-${HOMErrfs}/exec}
export FIXrrfs=${FIXrrfs:-${HOMErrfs}/fix}

export SHORTVER=$(echo "$rrfs_ver" | cut -d "." -f1-2)
export umbrella_forecast_data_base=${DATAROOT}/rrfs_forecast_${cyc}_${SHORTVER}/${WGF}

#################################### 
# Specify Timeout Behavior of Post
#
# SLEEP_TIME - Amount of time to wait for
#              any new log file before exiting
# SLEEP_INT  - Amount of time to wait between
#              checking for log files
####################################
export SLEEP_TIME=900
export SLEEP_INT=15

env

${HOMErrfs}/scripts/exrrfs_post_manager.sh
export err=$?; err_chk

msg="$job completed normally"
postmsg "$msg"          

##################################################
# Remove the Temporary working directory
##################################################
if [ "${KEEPDATA^^}" != YES ]; then
  cd $DATAROOT          
  rm -rf $DATA
fi
