#!/usr/bin/env bash
declare -rx PS4='+ $(basename ${BASH_SOURCE[0]:-${FUNCNAME[0]:-"Unknown"}})[${LINENO}]${id}: '
set -x
date
#
#-----------------------------------------------------------------------
# Specify Execution Areas
#-----------------------------------------------------------------------
#
export HOMErrfs=${HOMErrfs} #comes from the workflow at runtime
export EXECrrfs=${EXECrrfs:-${HOMErrfs}/exec}
export FIXrrfs=${FIXrrfs:-${HOMErrfs}/fix}
export PARMrrfs=${PARMrrfs:-${HOMErrfs}/parm}
export USHrrfs=${USHrrfs:-${HOMErrfs}/ush}
#
#-----------------------------------------------------------------------
# Obtain unique process id (pid) and create the run directory (DATA).
#-----------------------------------------------------------------------
#
export pid=${pid:-$$}
export RUN="rrfs"${WGF}
if [[ -z "${ENS_INDEX}" ]]; then
  export MEMID=""
else
  export MEMID="_m${ENS_INDEX}"
fi
export jobid=${jobid:-${RUN}_ic${MEMID}_${cyc}}
export DATA=${DATA:-${DATAROOT}/${jobid}}

if [ -d ${DATA} ]; then # remove the ${DATA} directory if existed
  rm -rf ${DATA}
fi
mkdir -p ${DATA}

export UMBRELLA_DATA=${UMBRELLA_DATA:-${DATAROOT}/umbrella}
#
#-----------------------------------------------------------------------
# Define COM directories
#-----------------------------------------------------------------------
#
export COMINrrfs=${COMINrrfs:-$(compath.py $envir/rrfs/$rrfs_ver)}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${rrfs_ver}/${RUN}.${PDY}/${cyc})}
mkdir -p ${COMOUT}${MEMDIR}/ic
#
#----------------------------------------
# Execute the script.
#----------------------------------------
#
export pgmout="${DATA}/OUTPUT.$$"
${HOMErrfs}/scripts/exrrfs_ic.sh
export err=$?; err_chk

if [ -e "$pgmout" ]; then
  cat $pgmout
fi
#
#----------------------------------------
# Remove the Temporary working directory
#----------------------------------------
#
cd ${DATAROOT}
[[ "${KEEPDATA}" == "NO" ]] && rm -rf ${DATA}
#
date
echo "JOB ${jobid:-} HAS COMPLETED NORMALLY!"
exit 0
