#!/bin/bash

date
export PS4=' $SECONDS + '
set -xue

#-----------------------------------------------------------------------
# RRFS File Service Manager
#-----------------------------------------------------------------------
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p ${DATA}
cd ${DATA}

#-----------------------------------------------------------------------
# Source the variable definitions file
#-----------------------------------------------------------------------
export WGF=${WGF:-"det"}
. ${HOMErrfs}/ush/rrfs_nco_config.sh

#-----------------------------------------------------------------------
# Source the variable definitions file
#-----------------------------------------------------------------------
export USHrrfs=${USHrrfs:-${HOMErrfs}/ush}
export PARMrrfs=${PARMrrfs:-${HOMErrfs}/parm}
export EXECrrfs=${EXECrrfs:-${HOMErrfs}/exec}
export FIXrrfs=${FIXrrfs:-${HOMErrfs}/fix}

#-----------------------------------------------------------------------
# Source the bash utility functions.
#-----------------------------------------------------------------------

. $USHrrfs/source_util_funcs.sh

export cycle="t${cyc}z"
setpdy.sh
. ./PDY
export CDATE=${PDY}${cyc}

${HOMErrfs}/scripts/exrrfs_fsm.sh
export err=$?; err_chk

if [ "${KEEPDATA}" != "YES" ]; then
  rm -rf ${DATA}
fi
