#!/usr/bin/env bash
declare -rx PS4='+ $(basename ${BASH_SOURCE[0]:-${FUNCNAME[0]:-"Unknown"}})[${LINENO}]: '
set -x
date
#
#-----------------------------------------------------------------------
# Specify Execution Areas
#-----------------------------------------------------------------------
#
export HOMErrfs=${HOMErrfs} #comes from the workflow at runtime
export EXECrrfs=${EXECrrfs:-${HOMErrfs}/exec}
export FIXrrfs=${FIXrrfs:-${HOMErrfs}/fix}
export PARMrrfs=${PARMrrfs:-${HOMErrfs}/parm}
export USHrrfs=${USHrrfs:-${HOMErrfs}/ush}
#
#-----------------------------------------------------------------------
#  find group information
#-----------------------------------------------------------------------
#
export GROUP_INDEX=${GROUP_INDEX:-1}
export GROUP_TOTAL_NUM=${GROUP_TOTAL_NUM:-1}
#
#-----------------------------------------------------------------------
# Obtain unique process id (pid) and create the run directory (DATA).
#-----------------------------------------------------------------------
#
export pid=${pid:-$$}
if [[ -z "${ENS_INDEX}" ]]; then
  export MEMDIR=""
else
  export MEMDIR="/mem${ENS_INDEX}"
fi
if [[ "${TYPE}" == "ic" ]]; then
  export jobid=${jobid:-ungrib_${cyc}}
else
  export jobid=${jobid:-ungrib_g${GROUP_INDEX}_${cyc}}
fi
export UMBRELLA_UNGRIB_DATA=${UMBRELLA_UNGRIB_DATA:-${DATAROOT}/${RUN}_ungrib_${TYPE}_${cyc}_${rrfs_ver}/${WGF}${MEMDIR}}
export DATA=${DATA:-${UMBRELLA_UNGRIB_DATA}/${jobid}}

if [[ -d "${DATA}" ]]; then # remove the ${DATA} directory if existed
  rm -rf "${DATA}"
fi
mkdir -p "${DATA}"
#
#-----------------------------------------------------------------------
# Set the parameters for the external model files.
#-----------------------------------------------------------------------
#
export EXTRN_MDL_SOURCE=${EXTRN_MDL_SOURCE:-"GFS"}
if [[ "${EXTRN_MDL_SOURCE}" == "GFS_NCO" ]]; then
  export COMINgfs=${COMINgfs:-$(compath.py "${envir}/gfs/${gfs_ver}")}
elif [[ "${EXTRN_MDL_SOURCE}" == "GEFS_NCO" ]]; then
  export COMINgefs=${COMINgefs:-$(compath.py "${envir}/gefs/${gefs_ver}")}
else
  export SOURCE_BASEDIR=${SOURCE_BASEDIR:-"SOURCE_BASEDIR_not_defined"}
fi
export OFFSET=${OFFSET:-0}
export LENGTH=${LENGTH:-0}
export INTERVAL=${INTERVAL:-1}
#
#-----------------------------------------------------------------------
# Define COM directories
#-----------------------------------------------------------------------
#
COMOUT=${COMOUT:-$(compath.py -o "${NET}/${rrfs_ver}/${RUN}.${PDY}/${cyc}")}
mkdir -p "${COMOUT}/ungrib_${TYPE}/${WGF}${MEMDIR}"
#
#----------------------------------------
# Execute the script.
#----------------------------------------
#
export pgmout="${DATA}/OUTPUT.$$"
"${HOMErrfs}"/scripts/exrrfs_ungrib.sh
export err=$?; err_chk

if [[ -e "${pgmout}" ]]; then
  cat "${pgmout}"
fi
#
#----------------------------------------
# Remove the Temporary working directory
#----------------------------------------
#
[[ "${KEEPDATA^^}" == "NO" ]] && rm -rf "${DATA}"
#
date
echo "JOB ${jobid:-} HAS COMPLETED NORMALLY!"
exit 0
