#!/bin/bash

#
#-----------------------------------------------------------------------
#
# This J-JOB script runs the GSI analysis 
#
#-----------------------------------------------------------------------

#
#-----------------------------------------------------------------------
#
# Source the variable definitions file and the bash utility functions.
#
#-----------------------------------------------------------------------
#
. ${GLOBAL_VAR_DEFNS_FP}
. $USHdir/source_util_funcs.sh
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
{ save_shell_opts; set -u -x; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Print message indicating entry into script.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs a analysis with FV3 for 
the specified cycle.
========================================================================"
#
#-----------------------------------------------------------------------
#
# Create the working directory under the cycle directory.
#
#-----------------------------------------------------------------------
# CYCLE_TYPE is to indicate which type of cycle this job for:
#   spinup: this job is for spin-up cycles
#   others(prod): this job is for product cycle
#
CYCLE_TYPE=${CYCLE_TYPE:-prod}
observer_nwges_dir=""

if [ ! -d "${SATBIAS_DIR}" ]; then
  echo "making satbias_dir directory for cycling bias correction files" 
  mkdir -p ${SATBIAS_DIR}
fi

#
#-----------------------------------------------------------------------
#
# create COMOUT directory
#
#-----------------------------------------------------------------------
#
if [ ${CYCLE_TYPE} == "spinup" ]; then
  COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/${cyc}_spinup${SLASH_ENSMEM_SUBDIR}"
else
  if [ ${MEM_TYPE} == "MEAN" ]; then
    COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/$cyc/ensmean"
  else
    COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/${cyc}${SLASH_ENSMEM_SUBDIR}"
  fi
fi
mkdir -p "${COMOUT}"
#
#-----------------------------------------------------------------------
#
# Call the ex-script for this J-job
#
#-----------------------------------------------------------------------
#
$SCRIPTSDIR/exrrfs_run_gsidiag.sh \
             cycle_dir="${CYCLE_DIR}" \
             cycle_type="${CYCLE_TYPE}" \
             gsi_type="${GSI_TYPE}" \
             mem_type="${MEM_TYPE}" \
             observer_nwges_dir="${observer_nwges_dir}" \
             comout="${COMOUT}" \
             satbias_dir="${SATBIAS_DIR}"
export err=$?; err_chk
#
#-----------------------------------------------------------------------
#
# Print exit message.
#
#-----------------------------------------------------------------------
#
print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/function.
#
#-----------------------------------------------------------------------
#
{ restore_shell_opts; } > /dev/null 2>&1

