#!/usr/bin/env bash
declare -rx PS4='+ $(basename ${BASH_SOURCE[0]:-${FUNCNAME[0]:-"Unknown"}})[${LINENO}]${id}: '
set -x
date
#
#-----------------------------------------------------------------------
# Specify Execution Areas
#-----------------------------------------------------------------------
#
export HOMErrfs=${HOMErrfs} #comes from the workflow at runtime
export EXECrrfs=${EXECrrfs:-${HOMErrfs}/exec}
export FIXrrfs=${FIXrrfs:-${HOMErrfs}/fix}
export PARMrrfs=${PARMrrfs:-${HOMErrfs}/parm}
export USHrrfs=${USHrrfs:-${HOMErrfs}/ush}
#
#-----------------------------------------------------------------------
# Obtain unique process id (pid) and create the run directory (DATA).
#-----------------------------------------------------------------------
#
export pid=${pid:-$$}
if [[ -z "${ENS_INDEX}" ]]; then
  export RUN="rrfs"
else
  export RUN="ensrrfs"
fi
export jobid=${jobid:-${RUN}_fcst_${cyc}}
export DATA=${DATA:-${DATAROOT}/${jobid}}

export UMBRELLA_DATA=${UMBRELLA_DATA:-${DATAROOT}/umbrella}
if [ -d ${UMBRELLA_DATA}/${jobid} ]; then
  rm -rf ${UMBRELLA_DATA}/${jobid}
fi
mkdir -p ${UMBRELLA_DATA}/${jobid}
#
#-----------------------------------------------------------------------
# Define COM directories
#-----------------------------------------------------------------------
#
export COMINrrfs=${COMINrrfs:-$(compath.py $envir/rrfs/$rrfs_ver)}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${rrfs_ver}/${RUN}.${PDY}/${cyc})}
if [[ -z "${ENS_INDEX}" ]]; then
  mkdir -p ${COMOUT}/fcst
else
  mkdir -p ${COMOUT}/mem${ENS_INDEX}/fcst
fi
#
#----------------------------------------
# Execute the script.
#----------------------------------------
export pgmout="${UMBRELLA_DATA}/${jobid}/OUTPUT.$$"
${HOMErrfs}/scripts/exrrfs_fcst_saveout.sh
export err=$?; err_chk

if [ -e "$pgmout" ]; then
  cat $pgmout
fi
#
date
echo "JOB ${jobid:-} HAS COMPLETED NORMALLY!"
exit 0
