#!/usr/bin/env bash
declare -rx PS4='+ $(basename ${BASH_SOURCE[0]:-${FUNCNAME[0]:-"Unknown"}})[${LINENO}]: '
set -x
date
#
#-----------------------------------------------------------------------
# Specify Execution Areas
#-----------------------------------------------------------------------
#
export HOMErrfs=${HOMErrfs} #comes from the workflow at runtime
export EXECrrfs=${EXECrrfs:-${HOMErrfs}/exec}
export FIXrrfs=${FIXrrfs:-${HOMErrfs}/fix}
export PARMrrfs=${PARMrrfs:-${HOMErrfs}/parm}
export USHrrfs=${USHrrfs:-${HOMErrfs}/ush}
#
#-----------------------------------------------------------------------
# Obtain unique process id (pid) and create the run directory (DATA).
#-----------------------------------------------------------------------
#
export pid=${pid:-$$}
if [[ -z "${ENS_INDEX}" ]]; then
  export MEMDIR=""
else
  export MEMDIR="/mem${ENS_INDEX}"
fi
# Do we need mpas_blend at spinup cycle?
if [[ "${SPINUP_MODE:-0}" == "1" ]];  then
  mpas_blend_str="mpas_blend_spinup"
else
  mpas_blend_str="mpas_blend"
fi

export UMBRELLA_PREP_IC_DATA=${UMBRELLA_PREP_IC_DATA:-${DATAROOT}/${RUN}_prep_ic_${cyc}_${rrfs_ver}/${WGF}${MEMDIR}}
export UMBRELLA_MPAS_BLEND_DATA=${UMBRELLA_MPAS_BLEND_DATA:-${DATAROOT}/${RUN}_${mpas_blend_str}_${cyc}_${rrfs_ver}/${WGF}${MEMDIR}}
export jobid=${jobid:-mpas_blend_${cyc}}
export DATA=${DATA:-${UMBRELLA_MPAS_BLEND_DATA}/${jobid}}

if [[ -d "${DATA}" ]]; then # remove the ${DATA} directory if existed
  rm -rf "${DATA}"
fi
mkdir -p "${DATA}"
#
#-----------------------------------------------------------------------
# Define COM directories
#-----------------------------------------------------------------------
#
export COMINrrfs=${COMINrrfs:-$(compath.py "${envir}/rrfs/${rrfs_ver}")}
export COMOUT=${COMOUT:-$(compath.py -o "${NET}/${rrfs_ver}/${RUN}.${PDY}/${cyc}")}
#
#----------------------------------------
# Execute the script.
#----------------------------------------
export pgmout="${DATA}/OUTPUT.$$"
"${HOMErrfs}"/scripts/exrrfs_mpas_blend.sh
export err=$?; err_chk

if [[ -e "${pgmout}" ]]; then
  cat "${pgmout}"
fi
#
#----------------------------------------
# Remove the Temporary working directory
#----------------------------------------
[[ "${KEEPDATA^^}" == "NO" ]] && rm -rf "${DATA}"
#
date
echo "JOB ${jobid:-} HAS COMPLETED NORMALLY!"
exit 0
