#!/bin/bash

date
export PS4='+ $SECONDS + ' 
set -xue

#-----------------------------------------------------------------------
# Specify Package Location
#-----------------------------------------------------------------------
export NET='rrfs'
export MACHINE="WCOSS2"
export WORKFLOW_MANAGER="ecflow"
export HOMErrfs=${HOMErrfs:-""}
export EXECrrfs=${EXECrrfs:-${HOMErrfs}/exec}
export FIXrrfs=${FIXrrfs:-${HOMErrfs}/fix}
export PARMrrfs=${PARMrrfs:-${HOMErrfs}/parm}
export USHrrfs=${USHrrfs:-${HOMErrfs}/ush}
export FIX_GSI="${FIXrrfs}/gsi"


#-----------------------------------------------------------------------
# RRFS Non-Var Cloud Analysis
#-----------------------------------------------------------------------
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}
case "${WGF}" in
  "det")
    export RUN="rrfs"
    ;;
  "enkf")
    export RUN="enkfrrfs"
    ;;
  "ensf")
    export RUN="refs"
    ;;
  "firewx")
    export RUN="firewx"
    ;;
esac
if [ $WGF = "enkf" ] || [ $WGF = "ensf" ]; then
  export ENSMEM_INDX=${MEMBER_NAME}
  export mem_num=m$(echo "${ENSMEM_INDX}")
  export DO_ENSEMBLE="TRUE"
else
  export ENSMEM_INDX=""
  export mem_num=""
  export DO_ENSEMBLE="FALSE"
fi

case $WGF in
  det)
    COM_WGF="rrfs"
    ;;
  enkf)
    COM_WGF="enkfrrfs"
    ;;
  ensf)
    COM_WGF="refs"
    ;;
  firewx)
    COM_WGF="firewx"
    ;;
esac

export CYCLE_TYPE=${CYCLE_TYPE:-prod}
export COMrrfs=${COMrrfs:-$(compath.py -o ${NET}/${rrfs_ver})}
if [ ${CYCLE_TYPE} = "spinup" ]; then
  export umbrella_analysis_data=${umbrella_analysis_data:-${DATAROOT}/rrfs_analysis_gsi_spinup_${cyc}_${rrfs_ver}/${WGF}}
  export umbrella_init_data=${umbrella_init_data:-${DATAROOT}/rrfs_init_spinup_${cyc}_${rrfs_ver}/${WGF}}
  export umbrella_forecast_data=${DATAROOT}/rrfs_forecast_spinup_${cyc}_${rrfs_ver}/${WGF}
else
  export umbrella_analysis_data=${umbrella_analysis_data:-${DATAROOT}/rrfs_analysis_gsi_${cyc}_${rrfs_ver}/${WGF}}
  export umbrella_init_data=${umbrella_init_data:-${DATAROOT}/rrfs_init_${cyc}_${rrfs_ver}/${WGF}}
  export umbrella_forecast_data=${DATAROOT}/rrfs_forecast_${cyc}_${rrfs_ver}/${WGF}
fi
if [ "${DO_ENSEMBLE}" = "TRUE" ]; then
  export umbrella_forecast_data=${umbrella_forecast_data}/${mem_num}
fi

#-----------------------------------------------------------------------
# Define forecast INPUT directories
#-----------------------------------------------------------------------
export FORECAST_INPUT_PRODUCT=${umbrella_forecast_data}/INPUT

#-----------------------------------------------------------------------
# Define data directories
#-----------------------------------------------------------------------
export shared_output_data=${umbrella_analysis_data}/output
export shared_output_data_init=${umbrella_init_data}/output
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p ${DATA} ${shared_output_data} ${shared_output_data_init} ${FORECAST_INPUT_PRODUCT}
cd ${DATA}

#-----------------------------------------------------------------------
# Set PDY and define COMOUT
#-----------------------------------------------------------------------
export cycle="t${cyc}z"
setpdy.sh
. ./PDY
export CDATE="${PDY}${cyc}"

if [ ${CYCLE_TYPE} = "spinup" ]; then
  export COMOUT=${COMrrfs}/${COM_WGF}.${PDY}/${cyc}_spinup
else
  export COMOUT=${COMrrfs}/${COM_WGF}.${PDY}/${cyc}
fi
if [ "${DO_ENSEMBLE}" = "TRUE" ]; then
  export COMOUT=${COMOUT}/${mem_num}
  export umbrella_forecast_data=${umbrella_forecast_data}/${mem_num}
fi
export COMOUT=${COMOUT}/analysis
mkdir -p ${COMOUT}

#-----------------------------------------------------------------------
# Source the bash utility functions.
#-----------------------------------------------------------------------

. $USHrrfs/source_util_funcs.sh

#-----------------------------------------------------------------------
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#-----------------------------------------------------------------------

scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )

#-----------------------------------------------------------------------
# Print message indicating entry into script.
#-----------------------------------------------------------------------

print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that runs a standalone Non-Var cloud
analysis with RRFS for the specified cycle.
========================================================================"

#-----------------------------------------------------------------------
# Execute the script.
#-----------------------------------------------------------------------

export pgmout="${DATA}/OUTPUT.$$"
env

$HOMErrfs/scripts/exrrfs_analysis_nonvarcld.sh
export err=$?; err_chk

if [ -e "$pgmout" ]; then
  cat $pgmout
fi

echo "ANALYSIS NONVARCLD job is completed" &> ${umbrella_init_data}/analysis_nonvarcld_${CYCLE_TYPE}_clean.flag

#-----------------------------------------------------------------------
# Print exit message.
#-----------------------------------------------------------------------

print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"

##################################################
# Remove the Temporary working directory
##################################################
if [ "${KEEPDATA^^}" != YES ]; then
  cd $DATAROOT
  rm -rf $DATA
fi
