#!/bin/bash

#-----------------------------------------------------------------------
# RRFS Save Restart
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Source the variable definitions file and the bash utility functions.
#-----------------------------------------------------------------------

. ${GLOBAL_VAR_DEFNS_FP}
. $USHdir/source_util_funcs.sh

date
export PS4='+ $SECONDS + '

#-----------------------------------------------------------------------
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#-----------------------------------------------------------------------

{ save_shell_opts; set -u -x; } > /dev/null 2>&1

#-----------------------------------------------------------------------
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#-----------------------------------------------------------------------

scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
scrfunc_fn=$( basename "${scrfunc_fp}" )
scrfunc_dir=$( dirname "${scrfunc_fp}" )

#-----------------------------------------------------------------------
# Print message indicating entry into script.
#-----------------------------------------------------------------------

print_info_msg "
========================================================================
Entering script:  \"${scrfunc_fn}\"
In directory:     \"${scrfunc_dir}\"

This is the J-job script for the task that saves restart files to nwges.
========================================================================"

#-----------------------------------------------------------------------
# Obtain unique process id (pid) and set the run directory (DATA).
#-----------------------------------------------------------------------

export pid=${pid:-$$}
export envir=${envir:-prod}
export RUN=${RUN:-rrfs}
export CDATE="${CDATE}"

export mem_num=m$(echo "${ENSMEM_INDX}")

export CYCLE_TYPE=${CYCLE_TYPE:-prod}
export CYCLE_SUBTYPE=${CYCLE_SUBTYPE:-empty}
export SURFACE_DIR=${SURFACE_DIR:-empty}
if [ "${CYCLE_TYPE}" = "spinup" ]; then
  if [ "${DO_ENSEMBLE}" = "TRUE" ]; then	# EnKF has spinup forecasts
    export DATA="${DATAROOT}/${RUN}_forecast_spinup_${mem_num}_${envir}_${cyc}"
    export NWGES_DIR="${GESROOT}/${RUN}.${PDY}/${cyc}/${mem_num}/forecast_spinup"
    if [ "${CYCLE_SUBTYPE}" = "ensinit" ]; then
      export DATA="${DATAROOT}/${RUN}_forecast_ensinit_${mem_num}_${envir}_${cyc}"
      export NWGES_DIR="${GESROOT}/${RUN}.${PDY}/${cyc}/${mem_num}/forecast_ensinit"
    fi
  else
    export DATA="${DATAROOT}/${RUN}_forecast_spinup_${envir}_${cyc}"
    export NWGES_DIR="${GESROOT}/${RUN}.${PDY}/${cyc}/forecast_spinup"
  fi
else
  if [ "${DO_ENSEMBLE}" = "TRUE" ]; then
    export DATA="${DATAROOT}/${RUN}_forecast_${mem_num}_${envir}_${cyc}"
    export NWGES_DIR="${GESROOT}/${RUN}.${PDY}/${cyc}/${mem_num}/forecast"
  else
    export DATA="${DATAROOT}/${RUN}_forecast_${envir}_${cyc}"
    export NWGES_DIR="${GESROOT}/${RUN}.${PDY}/${cyc}/forecast"
  fi
fi

mkdir -p "${NWGES_DIR}/RESTART"
mkdir -p "${NWGES_DIR}/INPUT"
if [ "${SURFACE_DIR}" != "empty" ]; then
  mkdir -p "${SURFACE_DIR}"
fi

len_ensmem=${#ENSMEM_INDX}
if [ ${len_ensmem} -le 3 ]; then
  CYCLE_SUBTYPE="control"
fi
cd ${SURFACE_DIR}

#-----------------------------------------------------------------------
# Make sure that fhr is a non-empty string consisting of only digits.  
#-----------------------------------------------------------------------

export fhr=$( printf "%s" "${fhr}" | sed -n -r -e "s/^([0-9]+)$/\1/p" )
if [ -z "$fhr" ]; then
  err_exit "\
The forecast hour (fhr) must be a non-empty string consisting of only 
digits:
  fhr = \"${fhr}\""
fi

#-----------------------------------------------------------------------
# Execute the script.
#-----------------------------------------------------------------------

export pgmout="${SURFACE_DIR}/OUTPUT.$$"
env

$SCRIPTSdir/exrrfs_save_restart.sh
export err=$?; err_chk

if [ -e "$pgmout" ]; then
  cat $pgmout
fi

if [ "${KEEPDATA}" = "NO" ]; then
  rm -rf ${DATA}
fi

#-----------------------------------------------------------------------
# Print exit message.
#-----------------------------------------------------------------------

print_info_msg "
========================================================================
Exiting script:  \"${scrfunc_fn}\"
In directory:    \"${scrfunc_dir}\"
========================================================================"

#-----------------------------------------------------------------------
# Restore the shell options saved at the beginning of this script/function.
#-----------------------------------------------------------------------

{ restore_shell_opts; } > /dev/null 2>&1

