#!/bin/bash
# shellcheck disable=all
# Usage: bkg_rrun_and_notify [sleeptime] [email=freq_in_seconds] [email_address] [email_tag]

sleeptime=60  # seconds
email_freq=-1
if (( $# > 0 )); then
  sleeptime=$1
  if ! [[ "${sleeptime}" =~ ^[0-9]+$ ]]; then  # if not a non-negative number
    sleeptime=60
  fi
  if [[ "$2" == *email* ]]; then
    email_freq=${2//[^0-9]/}  # get the seconds
    email_addr=$3
    email_tag=$4
  fi
fi

knt=0
while true; do
 rrun
 if (( 10#${email_freq} > 0 )); then
   if (( knt * sleeptime >= 10#${email_freq} )); then
     subject="session is alive: ${email_tag}"
     recipents="${email_addr} ${email_addr}"  # add additional email addresses if needed
     echo "-" | mail -s "${subject}" ${recipents}
     knt=1
   else
     (( knt += 1 ))
   fi
 fi

 sleep ${sleeptime}
done
