#!/bin/bash
# shellcheck disable=all

if [[ -s rrfs.xml ]]; then
  NET=rrfs
elif [[ -s rtma.xml ]]; then
  NET=rtma
elif [[ -s arps.xml ]]; then
  NET=arps
fi

if (( $# > 0 )); then
  xmlfile="$1/${NET}.xml"
else
  xmlfile="${NET}.xml"
fi

echo -e "======= metatasks ======"
grep "<metatask name=" ${xmlfile}

echo -e "\n======= tasks ======"
grep "<task name=" ${xmlfile}

echo -e "\n======= cycledefs ======"
grep "<cycledef group=" ${xmlfile}

if grep 'DO_CHEMISTRY</name><value>TRUE' ${xmlfile} &> /dev/null; then
  echo -e "\n======= DO_CHEMISTRY ======"
  grep "CHEM_GROUPS" ${xmlfile} | grep -oP '(?<=<value>).*?(?=</value>)'
fi

echo -e "\n======= any undefined variable? ======"
grep "_not_defined" ${xmlfile}
