#!/bin/bash
# shellcheck disable=all
# a wrapper to rocotoboot
# by Guoqing Ge, 2019/04
#
fulltasks="yes"
module load rocoto/1.3.7g
#known major xml files for different systems
xmlarray=("RTMA_3D.xml" "HRRR_primary.xml" "RAP_primary.xml" "FV3LAM_wflow.xml" "rrfs.xml")
get_parm_type(){
  local str=$1
  if [[ "${str##*.}" == "xml" ]]; then
    xmlfile=${str%.*}
  fi
}
get_parm_type "$1"

# if xmlfile is not specified
if [[ -z ${xmlfile} ]]; then
# find if there exists major xml files under current directory
  for s in ${xmlarray[@]}; do
    if [ -f $s ]; then
      xmlfile=${s%.*};found=true;break
    fi
  done
  if [ ! $found ]; then # check other xml files under current directory
    arr=(*.xml)
    len=${#arr[@]}
    if [ "${arr[0]}" == "*.xml" ]; then
      echo "No xml file under current directory"; exit
    elif [ $len -eq 1 ]; then
      xmlfile=${arr[0]}; xmlfile=${xmlfile%.*}
    else
      echo "specify which xml file to use"; ls -1 *.xml; exit
    fi
  fi
elif [[ ! -e "${xmlfile}.xml" ]]; then
  echo "${xmlfile}.xml: no such file"
  exit
fi
echo -e "\nrocotoboot -w ${xmlfile}.xml -d ${xmlfile}.db --harvest-only
