#!/bin/bash
# shellcheck disable=all
# a wrapper to rocotostat
# by Guoqing Ge, 2019/04
#
fulltasks="yes"
module load rocoto/1.3.7g
#known major xml files for different systems
xmlarray=("RTMA_3D.xml" "HRRR_primary.xml" "RAP_primary.xml" "FV3LAM_wflow.xml" "rrfs.xml")
# rstat [xmlfile] [offset] [cycles] [tasks] [-m=metatasks]
get_parm_type(){
  local str=$1
  if [[ "${str##*.}" == "xml" ]]; then
    xmlfile=${str%.*}
  elif [[ "${str}" == "-m="*  ]]; then
    metatasks=${str:3}
  elif [[ "${str}" == "-v10"  ]]; then
    verbose="-v 10"
  elif [[ "${str:0:1}" == "-" ]] || [[ "${str:0:1}" == "+" ]]; then
    offset="${str}"
  elif [[ "${str}" =~ ^[0-9]+$ ]] ; then # all digits
    if (( 10#${str} < 9999 )); then
      offset="${str}"
    else
      cycles="${str}"
    fi
  elif [[ "${str:0:12}" =~ ^[0-9]+$ ]] && [[ "${str:13:12}" =~ ^[0-9]+$ ]]; then
    cycles="${str}"
  elif [[ ! -z ${str} ]]; then
    tasks="${str}"
  #else # if $1 is empty, do nothing
  fi
}

get_parm_type "$1"
get_parm_type "$2"
get_parm_type "$3"
get_parm_type "$4"

# if xmlfile is not specified
if [[ -z ${xmlfile} ]]; then
# find if there exists major xml files under current directory
  for s in ${xmlarray[@]}; do
    if [ -f $s ]; then
      xmlfile=${s%.*};found=true;break
    fi
  done
  if [ ! $found ]; then # check other xml files under current directory
    arr=(*.xml)
    len=${#arr[@]}
    if [ "${arr[0]}" == "*.xml" ]; then
      echo "No xml file under current directory"; exit
    elif [ $len -eq 1 ]; then
      xmlfile=${arr[0]}; xmlfile=${xmlfile%.*}
    else
      echo "specify which xml file to use"; ls -1 *.xml; exit
    fi
  fi
elif [[ ! -e "${xmlfile}.xml" ]]; then
  echo "${xmlfile}.xml: no such file"
  exit
fi
echo "ok, work on ${xmlfile}.xml..."

# if cycles not specified 
if [[ -z "${cycles}" ]]; then # use current cycle or apply offset
  retro=$(grep 'workflow.*realtime="T"' ${xmlfile}.xml)
  if [[ -z "${retro}" ]] ; then
    all=$(rocotostat -w ${xmlfile}.xml -d ${xmlfile}.db -s |grep "  Active  " | cut -c1-12 | xargs -n 6)
    if [[ -z "${all}" ]]; then
      echo "This is a retro workflow, no active cycles, use rstat YYYYMMDDHH"
      rinfo
      exit
    fi
    cycles=${all:0:12}
    echo "curret cycle=${cycles} "
  else # realtime
    cycles=$(date -u +%Y%m%d%H00)
    echo "realtime workflow, current cycle= ${cycles}"
  fi
  if [[ ! -z ${offset} ]]; then
    cycles=$(date -ud "${cycles:0:8} ${cycles:8:2} ${offset} hours" +%Y%m%d%H00 )
    echo "offset=${offset} cycle: ${cycles}"
  fi
fi

if [[ ! -z ${metatasks} ]]; then # metatasks
  rocotostat ${verbose} -w ${xmlfile}.xml -d ${xmlfile}.db -c ${cycles} -m ${metatasks}
elif [[ ! -z ${tasks} ]]; then #tasks
  rocotostat ${verbose} -w ${xmlfile}.xml -d ${xmlfile}.db -c ${cycles} -t ${tasks}
else
  rocotostat ${verbose} -w ${xmlfile}.xml -d ${xmlfile}.db -c ${cycles}
fi
echo -e "\nrocotostat -w ${xmlfile}.xml -d ${xmlfile}.db [ -c cycles [-t tasks] ]"
