#!/usr/bin/env python
#
import sys
import os

args = sys.argv
nargs = len(args) - 1
if nargs < 2:
    print(f"{os.path.basename(sys.argv[0])} <satinfo_filename> <sis_str>")
    print(f'  eg: {os.path.basename(sys.argv[0])} satinfo "abi_g16,abi_g18,cris-fsr_n21"')
    exit()

yfile = args[1]
yfile2 = yfile + "_old001"
sis_list = [mysis.strip() for mysis in args[2].strip().split(',')]
#
# find an available file name to backup the old yaml file
if os.path.exists(yfile2):
    knt = 1
    yfile2 = f'{yfile}_old{knt:03}'
    while os.path.exists(yfile2):
        knt += 1
        yfile2 = f'{yfile}_old{knt:03}'
#
os.replace(yfile, yfile2)
with open(yfile2, 'r') as infile, open(yfile, 'w') as outfile:
    for line in infile:
        if line.strip().startswith("!"):
            outfile.write(line)
        else:
            found = False
            for sis in sis_list:
                if sis in line:
                    found = True
                    break
            if not found:
                outfile.write(line)
