#!/bin/bash
# shellcheck disable=all
# find the log file for a given task at a given cycle
# by Guoqing Ge, 2025/07
#
if [[ ! -s exp.setup ]]; then
  echo "Run this command under the expdir where exp.setup is located"
  exit
fi
source exp.setup
if [[ $# < 2 ]]; then
  echo "$(basename $0) <YYYYMMDDHH|YYYYMMDDHHmm> <task>"
  exit
fi

RUN=rrfs

CDATE=$1
taskraw=$2
task=${taskraw%_g*}
if [[ "${task}" == *prep_chem* ]]; then
  task="prep_chem"
fi
PDY=${CDATE:0:8}
cyc=${CDATE:8:2}
logroot=${COMROOT}/${NET}/${VERSION}/logs
logfile="${logroot}/${RUN}.${PDY}/${cyc}/${WGF}/${RUN}_${taskraw}_${TAG}_${PDY}${cyc}.log"
echo "----log file:"
ls ${logfile}*
echo "${logroot}/${RUN}.${PDY}/${cyc}/${WGF}/rrfs.log"

echo -e  "\n---com output:"
comout="${COMROOT}/${NET}/${VERSION}/${RUN}.${PDY}/${cyc}/${task}/${WGF}"
if [[ "${task}" == *pyDAmonitor* ]] || [[ "${task}" == *graphics* ]]; then
  comout=${comout%/*}
fi
echo "${comout}"
if [[ ! -d "${comout}" ]]; then
  echo " !!! the above directory either NOT created, or has been purged !!!"
fi

echo -e "\n---stmp output:"
stmpout="${DATAROOT}/${PDY}/${RUN}_${task}_${cyc}_${VERSION}/${WGF}"
if [[ "${task}" == *pyDAmonitor* ]]; then
  stmpout=${stmpout%/*}
fi
echo "${stmpout}"
if [[ ! -d "${stmpout}" ]]; then
  echo " !!! the above directory either NOT created, or has been purged !!!"
fi

