#
#-----------------------------------------------------------------------
#
# This file defines and then calls a function that sets parameters 
# associated with the external model used for initial conditions (ICs) 
# and the one used for lateral boundary conditions (LBCs).
#
#-----------------------------------------------------------------------
#
function set_extrn_mdl_params() {
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located 
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
local scrfunc_fp=$( readlink -f "${BASH_SOURCE[0]}" )
local scrfunc_fn=$( basename "${scrfunc_fp}" )
local scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Get the name of this function.
#
#-----------------------------------------------------------------------
#
local func_name="${FUNCNAME[0]}"
#
#-----------------------------------------------------------------------
#
# Set the system directory (i.e. location on disk, not on HPSS) in which
# the files generated by the external model specified by EXTRN_MDL_NAME_ICS 
# that are necessary for generating initial condition (IC) and surface 
# files for the FV3SAR are stored (usually for a limited time, e.g. for 
# the GFS external model, 2 weeks on WCOSS and 2 days on hera).  If for 
# a given cycle these files are available in this system directory, they 
# will be copied over to a subdirectory under the cycle directory.  If 
# these files are not available in the system directory, then we search 
# for them elsewhere, e.g. in the mass store (HPSS).
#
#-----------------------------------------------------------------------
#
case ${EXTRN_MDL_NAME_ICS} in

"GSMGFS")
  case $MACHINE in
  "WCOSS2")
    EXTRN_MDL_SYSBASEDIR_ICS=""
    ;;
  "HERA")
    EXTRN_MDL_SYSBASEDIR_ICS=""
    ;;
  "ORION"|"HERCULES")
    EXTRN_MDL_SYSBASEDIR_ICS=""
    ;;
  "JET")
    EXTRN_MDL_SYSBASEDIR_ICS=""
    ;;
  esac
  ;;

"FV3GFS")
  case $MACHINE in
  "WCOSS2")
    EXTRN_MDL_SYSBASEDIR_ICS="/lfs/h1/ops/prod/com/gfs/v16.3"
    ;;
  "HERA")
    EXTRN_MDL_SYSBASEDIR_ICS="/scratch1/NCEPDEV/rstprod/com/gfs/prod"
    ;;
  "ORION"|"HERCULES")
    EXTRN_MDL_SYSBASEDIR_ICS=""
    ;;
  "JET")
    EXTRN_MDL_SYSBASEDIR_ICS="/public/data/grids/gfs/0p25deg/grib2"
    ;;
  esac
  ;;

"GDASENKF")
  case "$MACHINE" in
  "WCOSS2")
    EXTRN_MDL_SYSBASEDIR_ICS="/lfs/h1/ops/prod/com/gfs/v16.3"
    ;;
  "HERA")
    EXTRN_MDL_SYSBASEDIR_ICS="/scratch1/NCEPDEV/rstprod/com/gfs/prod"
    ;;
  "JET")
    EXTRN_MDL_SYSBASEDIR_ICS="/mnt/lfs4/BMC/public/data/grids/enkf/atm"
    ;;
  esac
  ;;

"GEFS")
  case "$MACHINE" in
  "WCOSS2")
    EXTRN_MDL_SYSBASEDIR_ICS="${EXTRN_MDL_SOURCE_BASEDIR_ICS:-"/lfs/h1/ops/prod/com/gefs/v12.3"}"
    ;;
  "HERA")
    EXTRN_MDL_SYSBASEDIR_ICS=""
    ;;
  "JET")
    EXTRN_MDL_SYSBASEDIR_ICS="${EXTRN_MDL_SOURCE_BASEDIR_ICS:-"/mnt/lfs4/BMC/public/data/grids/gens/pgrb2b"}"
    ;;
  "HERA")
    EXTRN_MDL_SYSBASEDIR_ICS="${EXTRN_MDL_SOURCE_BASEDIR_ICS:-/mnt/lfs4/BMC/public/data/grids/gens/pgrb2b}"
    ;;
  esac
  ;;

"RAP")
  case $MACHINE in
  "HERA")
    EXTRN_MDL_SYSBASEDIR_ICS="/scratch2/BMC/public/data/gsd/rap/full/wrfnat"
    ;;
  "ORION"|"HERCULES")
    EXTRN_MDL_SYSBASEDIR_ICS=""
    ;;
  "JET")
    EXTRN_MDL_SYSBASEDIR_ICS="/public/data/grids/rap/full/wrfnat/grib2"
    ;;
  esac
  ;;

"HRRR")
  case $MACHINE in
  "HERA")
    EXTRN_MDL_SYSBASEDIR_ICS="/scratch2/BMC/public/data/gsd/hrrr/conus/wrfnat"
    ;;
  "ORION"|"HERCULES")
    EXTRN_MDL_SYSBASEDIR_ICS=""
    ;;
  "JET")
    EXTRN_MDL_SYSBASEDIR_ICS="/public/data/grids/hrrr/conus/wrfnat/grib2"
    ;;
  esac
  ;;

"HRRRDAS")
  case "$MACHINE" in
  "HERA")
    EXTRN_MDL_SYSBASEDIR_ICS=""
    ;;
  "JET")
    EXTRN_MDL_SYSBASEDIR_ICS="/mnt/lfs1/BMC/wrfruc/HRRRE/cycle"
    ;;
  esac
  ;;

"RRFS")
  case "$MACHINE" in
  "WCOSS2")
    EXTRN_MDL_SYSBASEDIR_ICS="/lfs/h2/emc/ptmp/emc.lam/rrfs/na/prod"
  esac
  ;;

esac

#
#  for retro, the external boundary could come from other location.
#
if [[ "${DO_RETRO}" == "TRUE" && ! -z "${EXTRN_MDL_SOURCE_BASEDIR_ICS}" ]]; then
      EXTRN_MDL_SYSBASEDIR_ICS="${EXTRN_MDL_SOURCE_BASEDIR_ICS}"
fi

#
# If EXTRN_MDL_SYSBASEDIR_ICS has not been set (not even to a null string), 
# print out an error message and exit.
#
if [ -z "${EXTRN_MDL_SYSBASEDIR_ICS+x}" ]; then
  print_err_msg_exit "\
The variable EXTRN_MDL_SYSBASEDIR_ICS specifying the system directory
in which to look for the files generated by the external model for ICs
has not been set for the current combination of machine (MACHINE) and 
external model (EXTRN_MDL_NAME_ICS):
  MACHINE = \"$MACHINE\"
  EXTRN_MDL_NAME_ICS = \"${EXTRN_MDL_NAME_ICS}\""
fi
#
#-----------------------------------------------------------------------
#
# Set EXTRN_MDL_LBCS_OFFSET_HRS, which is the number of hours to shift 
# the starting time of the external model that provides lateral boundary 
# conditions.
#
#-----------------------------------------------------------------------
#
if [[ -z ${EXTRN_MDL_LBCS_OFFSET_HRS} ]]; then
  case ${EXTRN_MDL_NAME_LBCS} in
    "GSMGFS")
      EXTRN_MDL_LBCS_OFFSET_HRS="0"
      ;;
    "FV3GFS")
      EXTRN_MDL_LBCS_OFFSET_HRS="0"
      ;;
    "GDASENKF")
      EXTRN_MDL_LBCS_OFFSET_HRS="6"
      ;;
    "GEFS")
      EXTRN_MDL_LBCS_OFFSET_HRS="6"
      ;;
    "RAP")
      EXTRN_MDL_LBCS_OFFSET_HRS="3"
      ;;
    "HRRR")
      EXTRN_MDL_LBCS_OFFSET_HRS="0"
      ;;
    "RRFS")
      EXTRN_MDL_LBCS_OFFSET_HRS="0"
      ;;
  esac
fi
#
#-----------------------------------------------------------------------
#
# Set the system directory (i.e. location on disk, not on HPSS) in which
# the files generated by the external model specified by EXTRN_MDL_NAME_LBCS 
# that are necessary for generating lateral boundary condition (LBC) files 
# for the FV3SAR are stored (usually for a limited time, e.g. for the GFS 
# external model, 2 weeks on WCOSS and 2 days on hera).  If for a given 
# cycle these files are available in this system directory, they will be 
# copied over to a subdirectory under the cycle directory.  If these files 
# are not available in the system directory, then we search for them 
# elsewhere, e.g. in the mass store (HPSS).
#
#-----------------------------------------------------------------------
#
case ${EXTRN_MDL_NAME_LBCS} in

"GSMGFS")
  case $MACHINE in
  "WCOSS2")
    EXTRN_MDL_SYSBASEDIR_LBCS=""
    ;;
  "HERA")
    EXTRN_MDL_SYSBASEDIR_LBCS=""
    ;;
  "ORION"|"HERCULES")
    EXTRN_MDL_SYSBASEDIR_LBCS=""
    ;;
  "JET")
    EXTRN_MDL_SYSBASEDIR_LBCS=""
    ;;
  esac
  ;;

"FV3GFS")
  case $MACHINE in
  "WCOSS2")
    EXTRN_MDL_SYSBASEDIR_LBCS="/lfs/h1/ops/prod/com/gfs/v16.3"
    ;;
  "HERA")
    EXTRN_MDL_SYSBASEDIR_LBCS="/scratch1/NCEPDEV/rstprod/com/gfs/prod"
    ;;
  "ORION"|"HERCULES")
    EXTRN_MDL_SYSBASEDIR_LBCS=""
    ;;
  "JET")
    EXTRN_MDL_SYSBASEDIR_LBCS="/public/data/grids/gfs/0p25deg/grib2"
    ;;
  esac
  ;;

"GDASENKF")
  case "$MACHINE" in
  "HERA")
    EXTRN_MDL_SYSBASEDIR_LBCS="/scratch1/NCEPDEV/rstprod/com/gfs/prod"
    ;;
  "JET")
    EXTRN_MDL_SYSBASEDIR_LBCS="/mnt/lfs4/BMC/public/data/grids/enkf/atm"
    ;;
  esac
  ;;

"GEFS")
  case "$MACHINE" in
  "WCOSS2")
    EXTRN_MDL_SYSBASEDIR_LBCS="${EXTRN_MDL_SOURCE_BASEDIR_LBCS:-"/lfs/h1/ops/prod/com/gefs/v12.3"}"
    ;;
  "JET")
    EXTRN_MDL_SYSBASEDIR_LBCS="${EXTRN_MDL_SOURCE_BASEDIR_LBCS:-"/mnt/lfs4/BMC/public/data/grids/gens/pgrb2b"}"
    ;;
  "HERA")
    EXTRN_MDL_SYSBASEDIR_LBCS="${EXTRN_MDL_SOURCE_BASEDIR_LBCS:-/mnt/lfs4/BMC/public/data/grids/gens/pgrb2b}"
    ;;
  esac
  ;;

"RAP")
  case $MACHINE in
  "HERA")
    EXTRN_MDL_SYSBASEDIR_LBCS="/scratch2/BMC/public/data/gsd/rap/full/wrfnat"
    ;;
  "ORION"|"HERCULES")
    EXTRN_MDL_SYSBASEDIR_LBCS=""
    ;;
  "JET")
    EXTRN_MDL_SYSBASEDIR_LBCS="/public/data/grids/rap/full/wrfnat/grib2"
    ;;
  esac
  ;;

"HRRR")
  case $MACHINE in
  "HERA")
    EXTRN_MDL_SYSBASEDIR_LBCS="/scratch2/BMC/public/data/gsd/hrrr/conus/wrfnat"
    ;;
  "ORION"|"HERCULES")
    EXTRN_MDL_SYSBASEDIR_LBCS=""
    ;;
  "JET")
    EXTRN_MDL_SYSBASEDIR_LBCS="/public/data/grids/hrrr/conus/wrfnat/grib2"
    ;;
  esac
  ;;

"RRFS")
  case $MACHINE in
  "WCOSS2")
    EXTRN_MDL_SYSBASEDIR_LBCS="/lfs/h2/emc/ptmp/emc.lam/rrfs/na/prod"
    ;;
  esac
  ;;

esac

if [[ "${DO_RETRO}" == "TRUE" && ! -z "${EXTRN_MDL_SOURCE_BASEDIR_LBCS}" ]]; then
      EXTRN_MDL_SYSBASEDIR_LBCS="${EXTRN_MDL_SOURCE_BASEDIR_LBCS}"
fi

#
# If EXTRN_MDL_SYSBASEDIR_LBCS has not been set (not even to a null string), 
# print out an error message and exit.
#
if [ -z "${EXTRN_MDL_SYSBASEDIR_LBCS+x}" ]; then
  print_err_msg_exit "\
The variable EXTRN_MDL_SYSBASEDIR_LBCS specifying the system directory
in which to look for the files generated by the external model for LBCs
has not been set for the current combination of machine (MACHINE) and 
external model (EXTRN_MDL_NAME_LBCS):
  MACHINE = \"$MACHINE\"
  EXTRN_MDL_NAME_LBCS = \"${EXTRN_MDL_NAME_LBCS}\""
fi
}
#
#-----------------------------------------------------------------------
#
# Call the function defined above.
#
#-----------------------------------------------------------------------
#
set_extrn_mdl_params
