unload("PrgEnv-intel")
unload("netcdf")

load(pathJoin("PrgEnv-intel", os.getenv("PrgEnv_intel_ver")))
load(pathJoin("intel", os.getenv("intel_ver")))
load(pathJoin("craype", os.getenv("craype_ver")))
load(pathJoin("python", os.getenv("python_ver")))
load(pathJoin("prod_util", os.getenv("prod_util_ver")))
load(pathJoin("cray-mpich", os.getenv("cray_mpich_ver")))
load(pathJoin("cray-pals", os.getenv("cray_pals_ver")))

load(pathJoin("hdf5-D", os.getenv("hdf5_ver")))
load(pathJoin("netcdf-D", os.getenv("netcdf_ver")))
load(pathJoin("pnetcdf-D", os.getenv("pnetcdf_ver")))
load(pathJoin("gempak", os.getenv("gempak_ver")))
