load(pathJoin("PrgEnv-intel", os.getenv("PrgEnv_intel_ver")))
load(pathJoin("intel", os.getenv("intel_ver")))
load(pathJoin("craype", os.getenv("craype_ver")))
load(pathJoin("python", os.getenv("python_ver")))
load(pathJoin("prod_util", os.getenv("prod_util_ver")))
load(pathJoin("cray-mpich", os.getenv("cray_mpich_ver")))
load(pathJoin("cray-pals", os.getenv("cray_pals_ver")))

load(pathJoin("libjpeg", os.getenv("libjpeg_ver")))
load(pathJoin("hdf5-D", os.getenv("hdf5_ver")))
load(pathJoin("netcdf-D", os.getenv("netcdf_ver")))
load(pathJoin("pnetcdf-D", os.getenv("pnetcdf_ver")))
load(pathJoin("bacio", os.getenv("bacio_ver")))
load(pathJoin("w3emc", os.getenv("w3emc_ver")))
load(pathJoin("nemsio", os.getenv("nemsio_ver")))
load(pathJoin("sp", os.getenv("sp_ver")))
load(pathJoin("ip", os.getenv("ip_ver")))
load(pathJoin("g2", os.getenv("g2_ver")))
load(pathJoin("esmf-D", os.getenv("esmf_ver")))

load(pathJoin("udunits", os.getenv("udunits_ver")))
load(pathJoin("gsl", os.getenv("gsl_ver")))
load(pathJoin("nco", os.getenv("nco_ver")))

