# This workflow will install Python dependencies, and run flake8 for syntax errors only.
#
# Edward Hartnett, 9/9/24

name: flake8

on:
  push:
    branches: [ "dev-sci" ]
  pull_request:
    branches: [ "dev-sci" ]

permissions:
  contents: read

jobs:
  flake8_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov coverage numpy netCDF4 jinja2
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors
        flake8 . --count --select=E9,F63,F7 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: pytest
      run: |
        pytest
