help([[
This loads libraries for building the RRFS workflow on the 
NOAA operational machine WCOSS2 (Catcus/Dogwood)
]])

whatis([===[Loads libraries needed for building the RRFS workflow on WCOSS2 ]===])

prepend_path("MODULEPATH", "/apps/ops/test/spack-stack-1.6.0-nco/envs/nco-intel-19.1.3.304/install/modulefiles/Core")
load(pathJoin("envvar", os.getenv("envvar_ver")))
load(pathJoin("PrgEnv-intel", os.getenv("PrgEnv_intel_ver")))
load(pathJoin("stack-intel", os.getenv("intel_ver")))
load(pathJoin("craype", os.getenv("craype_ver")))
load(pathJoin("stack-cray-mpich", os.getenv("cray_mpich_ver")))
load(pathJoin("stack-python", os.getenv("python_ver") or "3.10.13"))
load(pathJoin("cmake", os.getenv("cmake_ver")))
prepend_path("MODULEPATH", os.getenv("modulepath_compiler"))
prepend_path("MODULEPATH", os.getenv("modulepath_mpi"))
load(pathJoin("jasper", os.getenv("jasper_ver")))
load(pathJoin("zlib", os.getenv("zlib_ver")))
load(pathJoin("libpng", os.getenv("libpng_ver")))
load(pathJoin("parallel-netcdf", os.getenv("pnetcdf_ver")))
load(pathJoin("parallelio", os.getenv("pio_ver")))
load(pathJoin("wgrib2", os.getenv("wgrib2_ver")))
setenv("Jasper_ROOT",os.getenv("modulepath_jasper"))
setenv("NETCDF",os.getenv("modulepath_netcdf"))
setenv("PNETCDF",os.getenv("modulepath_pnetcdf"))
setenv("CMAKE_C_COMPILER","cc")
setenv("CMAKE_CXX_COMPILER","CC")
setenv("CMAKE_Fortran_COMPILER","ftn")
